import { useState } from 'react';
import { Pause, Play, RotateCcw, Square } from 'lucide-react';
import type { Chapter, ManuscriptAnalysisArtifact, ManuscriptAnalysisCompletionReport, ManuscriptAnalysisDraftLedgerEntry, ManuscriptAnalysisJob, ManuscriptAnalysisPhase, ManuscriptAnalysisPhaseResult, ManuscriptAnalysisUnit, ManuscriptStructureProposal } from '../../types/domain';
import type { ManuscriptReviewArtifactDetail } from '../../services/manuscriptAnalysis';

interface Props {
  job: ManuscriptAnalysisJob;
  units: ManuscriptAnalysisUnit[];
  draftLedger?: ManuscriptAnalysisDraftLedgerEntry[];
  phaseResults?: ManuscriptAnalysisPhaseResult[];
  artifacts?: ManuscriptAnalysisArtifact[];
  completionReport?: ManuscriptAnalysisCompletionReport;
  reviewDetails?: ManuscriptReviewArtifactDetail[];
  structureProposals?: ManuscriptStructureProposal[];
  chapters?: Chapter[];
  onReviewStructureProposal?: (id: string, status: ManuscriptStructureProposal['reviewStatus'], manualChanges?: Record<string, unknown>) => Promise<void>;
  onApplyStructure?: (runId: string) => void;
  onReviewArtifact?: (id: string, status: ManuscriptAnalysisArtifact['reviewStatus'], skipped?: boolean) => Promise<void>;
  onReviewDraft?: (id: string, status: ManuscriptAnalysisDraftLedgerEntry['status']) => Promise<void>;
  onOpenSource?: (sourceReferenceId: string) => void;
  error?: string;
  onResume: () => void;
  onRetry: () => void;
  onPause: () => void;
  onCancel: () => void;
  onCompleteReview: (explicitlySkip?: boolean) => void;
}

export function ManuscriptAnalysisProgress({ job, units, draftLedger = [], phaseResults = [], artifacts = [], completionReport, reviewDetails = [], structureProposals = [], chapters = [], onReviewStructureProposal, onApplyStructure, onReviewArtifact, onReviewDraft, onOpenSource, error, onResume, onRetry, onPause, onCancel, onCompleteReview }: Props) {
  const [confirmSkip, setConfirmSkip] = useState(false);
  const current = job.currentUnitId ? units.find((unit) => unit.id === job.currentUnitId) : undefined;
  const chapterIds = [...new Set(units.map((unit) => unit.chapterId))];
  const currentChapter = current ? units.filter((unit) => unit.chapterId === current.chapterId).findIndex((unit) => unit.id === current.id) + 1 : 0;
  const currentChapterNumber = current ? chapterIds.indexOf(current.chapterId) + 1 : 0;
  const failed = units.find((unit) => unit.status === 'failed');
  const pendingArtifacts = artifacts.filter((artifact) => artifact.reviewStatus === 'pending');
  const pendingDrafts = draftLedger.filter((entry) => entry.status === 'proposed' || entry.status === 'uncertain');
  const active = job.status === 'running';
  const phaseLabels: Record<ManuscriptAnalysisPhase, string> = { structure: 'Manuskript eingelesen', passage_continuity: 'Prüfeinheiten analysiert', bible_extraction: 'Bible-Vorschläge', character_memory: 'Character Memories', scene_or_chapter_synthesis: 'Kapitel-Synthesen', narrative_summaries: 'Zusammenfassungen', plot_thread_synthesis: 'Handlungsstränge', book_end_state: 'Buch-Endzustand', global_countercheck: 'Globale Gegenprüfung', user_review: 'Review', completed: 'Abgeschlossen' };
  const reviewable = artifacts.filter((artifact) => artifact.reviewStatus === 'pending');
  const reportSummary = completionReport ? `Abschlussbericht: ${completionReport.payload.recognizedScenes.length} Szenen, ${completionReport.payload.continuityFindings.length} Findings${completionReport.payload.truncations.length ? ` · ${completionReport.payload.truncations.length} Kürzungen protokolliert` : ''}` : undefined;
  const structureChapterIds = [...new Set(structureProposals.map((proposal) => proposal.chapterId))];
  return <section className="provider-notice manuscript-analysis-progress" role="status" aria-label={reportSummary}>
    <div><strong>Manuskript-Analyse</strong><span>Phase: {phaseLabels[job.currentPhase]} · Kapitel {currentChapterNumber || '—'} von {chapterIds.length} · Prüfeinheit {currentChapter || job.completedUnits} von {job.totalUnits}</span><span>{job.completedUnits} abgeschlossen · {job.failedUnits} fehlgeschlagen · {units.filter((unit) => unit.status === 'pending').length} offen · Provider {job.providerId}</span>{Object.entries(job.phaseProgress).length > 0 && <div className="manuscript-analysis-phases">{(Object.entries(job.phaseProgress) as Array<[ManuscriptAnalysisPhase, NonNullable<ManuscriptAnalysisJob['phaseProgress'][ManuscriptAnalysisPhase]>]>).map(([phase, progress]) => <span key={phase}>{phaseLabels[phase]}: {progress.completedUnits}/{progress.totalUnits} · {progress.status}</span>)}</div>}{phaseResults.length > 0 && <div className="manuscript-analysis-phases"><strong>Jobgebundene Ergebnisse</strong>{phaseResults.map((result) => <span key={result.id}>{phaseLabels[result.phase]} · {result.resultKind} · {artifacts.filter((artifact) => artifact.phase === result.phase && artifact.reviewStatus === 'pending').length} offen</span>)}</div>}{failed && <span className="save-error">Fehler in Kapitel {failed.chapterId}{failed.pageNumber === undefined ? '' : ` · Seite ${failed.pageNumber}`} · {failed.errorCode ?? 'ANALYSIS_FAILED'} · Provider {failed.actualProvider ?? failed.requestedProvider ?? job.providerId} · {new Date(failed.updatedAt).toLocaleString('de-DE')}: {failed.errorMessage ?? 'Unbekannter Fehler'}</span>}{error && <span className="save-error">{error}</span>}</div>
    {job.status === 'awaiting_user_review' && <div className="manuscript-import-review"><strong>Zentrales Importreview</strong><span>{reviewable.length} offene Artefakte · {pendingDrafts.length} offene Draft-Zustände. Jede Entscheidung bleibt jobgebunden.</span>{reviewable.map((artifact) => { const detail = reviewDetails.find((item) => item.artifactId === artifact.artifactId && item.artifactType === artifact.artifactType); return <article className="structure-proposal" key={artifact.id}><div><strong>{detail?.title ?? artifact.artifactType}</strong><span>{artifact.phase}{artifact.unitId ? ` · Einheit ${artifact.unitId}` : ''}{detail?.chapterId ? ` · Kapitel ${detail.chapterId}` : ''}{detail?.sceneId ? ` · Szene ${detail.sceneId}` : ''}{detail?.confidence === undefined ? '' : ` · ${Math.round(detail.confidence * 100)} % Confidence`}</span><p>{detail?.body ?? `Artefakt ${artifact.artifactId}`}</p>{detail?.reason && <p><strong>Begründung:</strong> {detail.reason}</p>}{detail?.excerpt && <blockquote>{detail.excerpt}</blockquote>}{detail?.sourceReferenceId && <><span>Quelle: {detail.sourceReferenceId} · Position {detail.startOffset ?? '—'}–{detail.endOffset ?? '—'}</span>{onOpenSource && <button className="text-button" onClick={() => onOpenSource(detail.sourceReferenceId!)}>Quelle öffnen</button>}</>}</div><div className="longform-actions">{onReviewArtifact && <><button className="ghost-button" onClick={() => void onReviewArtifact(artifact.id, 'confirmed')}>Fachlich bestätigen</button><button className="text-button" onClick={() => void onReviewArtifact(artifact.id, 'uncertain')}>Unsicher speichern</button><button className="text-button" onClick={() => void onReviewArtifact(artifact.id, 'rejected')}>Ablehnen</button></>}</div></article>; })}{pendingDrafts.map((entry) => <article className="structure-proposal" key={entry.id}><div><strong>Continuity State</strong><span>{entry.stateKind} · {entry.entityId}</span><p>{entry.previousState} → {entry.newState} · {entry.sourceExcerpt}</p></div><div className="longform-actions">{onReviewDraft && <><button className="ghost-button" onClick={() => void onReviewDraft(entry.id, 'confirmed')}>Bestätigen</button><button className="text-button" onClick={() => void onReviewDraft(entry.id, 'uncertain')}>Unsicher</button><button className="text-button" onClick={() => void onReviewDraft(entry.id, 'rejected')}>Ablehnen</button></>}</div></article>)}<div className="manuscript-analysis-report"><strong>Abschlussbericht-Vorschau</strong><span>Kapitel {chapterIds.length} · Prüfeinheiten {units.length} · Review-Daten {reviewDetails.length} · offene Entscheidungen {reviewable.length + pendingDrafts.length}</span></div></div>}
    {structureProposals.length > 0 && <div className="manuscript-structure-review"><strong>Strukturvorschau · semantische Szenenvorschläge</strong><span>{structureChapterIds.filter((chapterId) => structureProposals.filter((proposal) => proposal.chapterId === chapterId).every((proposal) => ['accepted', 'edited'].includes(proposal.reviewStatus))).length} von {structureChapterIds.length} Kapiteln geprüft. Die Passageanalyse bleibt bis zur Gesamtübernahme blockiert.</span>{structureChapterIds.map((chapterId) => { const proposals = structureProposals.filter((proposal) => proposal.chapterId === chapterId); const chapter = chapters.find((item) => item.id === chapterId); return <details open key={chapterId}><summary>Kapitel {chapter?.orderIndex ?? '—'} · {chapter?.title ?? chapterId} · {proposals.every((proposal) => ['accepted', 'edited'].includes(proposal.reviewStatus)) ? 'geprüft' : 'offen'}</summary>{proposals.map((proposal) => <article key={proposal.id} className="structure-proposal"><div><strong>{proposal.title}</strong><span>Position {proposal.startOffset}–{proposal.endOffset} · POV {proposal.povCharacterName ?? '—'} · Ort {proposal.location || '—'} · Zeit {proposal.storyTime || '—'} · {Math.round(proposal.confidence * 100)} % Confidence</span><p><strong>Ziel:</strong> {proposal.goal || '—'} · <strong>Konflikt:</strong> {proposal.conflict || '—'}</p><p>{proposal.boundaryReason}</p><blockquote>{proposal.evidenceExcerpt}</blockquote></div>{onReviewStructureProposal && <div className="longform-actions"><button className="ghost-button" onClick={() => void onReviewStructureProposal(proposal.id, 'accepted')}>Akzeptieren</button><button className="text-button" onClick={() => void onReviewStructureProposal(proposal.id, 'edited', { isImplicit: true })}>Als implizite Szene behalten</button><button className="text-button" onClick={() => void onReviewStructureProposal(proposal.id, 'uncertain')}>Unsicher</button><button className="text-button" onClick={() => void onReviewStructureProposal(proposal.id, 'rejected')}>Verwerfen</button></div>}</article>)}</details>; })}{job.status === 'awaiting_structure_review' && onApplyStructure && <div className="longform-actions"><button className="ghost-button" disabled={structureChapterIds.length === 0 || structureProposals.some((proposal) => !['accepted', 'edited'].includes(proposal.reviewStatus))} onClick={() => onApplyStructure(structureProposals[0]!.runId)}>Gesamte Struktur übernehmen und Analyse starten</button></div>}</div>}
    <div className="longform-actions"><button className="ghost-button" disabled={active || job.status === 'awaiting_user_review'} onClick={onResume}><Play size={14} /> Analyse fortsetzen</button><button className="ghost-button" disabled={job.failedUnits === 0 || active} onClick={onRetry}><RotateCcw size={14} /> Fehlgeschlagene erneut prüfen</button><button className="ghost-button" disabled={!active} onClick={onPause}><Pause size={14} /> Analyse pausieren</button><button className="text-button" disabled={job.status === 'cancelled' || job.status === 'completed'} onClick={onCancel}><Square size={14} /> Analyse abbrechen</button>{job.status === 'awaiting_user_review' && (!confirmSkip ? <button className="ghost-button" onClick={() => setConfirmSkip(true)}>Offene Ergebnisse überspringen</button> : <><span>Wirklich {pendingArtifacts.length + pendingDrafts.length} offene Ergebnisse überspringen?</span><button className="ghost-button" onClick={() => { setConfirmSkip(false); onCompleteReview(true); }}>Ja, auditieren und überspringen</button><button className="text-button" onClick={() => setConfirmSkip(false)}>Abbrechen</button></>)}</div>
  </section>;
}
