import { useState } from 'react';
import { Pause, Play, RotateCcw, Square } from 'lucide-react';
import type { ManuscriptAnalysisArtifact, ManuscriptAnalysisDraftLedgerEntry, ManuscriptAnalysisJob, ManuscriptAnalysisPhase, ManuscriptAnalysisPhaseResult, ManuscriptAnalysisUnit, ManuscriptStructureProposal } from '../../types/domain';

interface Props { job: ManuscriptAnalysisJob; units: ManuscriptAnalysisUnit[]; draftLedger?: ManuscriptAnalysisDraftLedgerEntry[]; phaseResults?: ManuscriptAnalysisPhaseResult[]; artifacts?: ManuscriptAnalysisArtifact[]; structureProposals?: ManuscriptStructureProposal[]; onReviewStructureProposal?: (id: string, status: ManuscriptStructureProposal['reviewStatus']) => Promise<void>; onReviewArtifact?: (id: string, status: ManuscriptAnalysisArtifact['reviewStatus'], skipped?: boolean) => Promise<void>; onReviewDraft?: (id: string, status: ManuscriptAnalysisDraftLedgerEntry['status']) => Promise<void>; error?: string; onResume: () => void; onRetry: () => void; onPause: () => void; onCancel: () => void; onCompleteReview: (explicitlySkip?: boolean) => void; }

export function ManuscriptAnalysisProgress({ job, units, draftLedger = [], phaseResults = [], artifacts = [], structureProposals = [], onReviewStructureProposal, onReviewArtifact, onReviewDraft, error, onResume, onRetry, onPause, onCancel, onCompleteReview }: Props) {
  const [confirmSkip, setConfirmSkip] = useState(false);
  const current = job.currentUnitId ? units.find((unit) => unit.id === job.currentUnitId) : undefined;
  const currentChapter = current ? units.filter((unit) => unit.chapterId === current.chapterId).findIndex((unit) => unit.id === current.id) + 1 : 0;
  const chapters = new Set(units.map((unit) => unit.chapterId)).size;
  const currentChapterNumber = current ? [...new Set(units.map((unit) => unit.chapterId))].indexOf(current.chapterId) + 1 : 0;
  const failed = units.find((unit) => unit.status === 'failed');
  const pendingArtifacts = artifacts.filter((artifact) => artifact.reviewStatus === 'pending');
  const pendingDrafts = draftLedger.filter((entry) => entry.status === 'proposed' || entry.status === 'uncertain');
  const active = job.status === 'running';
  const phaseLabels: Record<ManuscriptAnalysisPhase, string> = { structure: 'Manuskript eingelesen', passage_continuity: 'Prüfeinheiten analysiert', bible_extraction: 'Bible-Vorschläge', character_memory: 'Character Memories', scene_or_chapter_synthesis: 'Kapitel-Synthesen', narrative_summaries: 'Zusammenfassungen', plot_thread_synthesis: 'Handlungsstränge', book_end_state: 'Buch-Endzustand', global_countercheck: 'Globale Gegenprüfung', user_review: 'Review', completed: 'Abgeschlossen' };
  const reviewable = artifacts.filter((artifact) => artifact.reviewStatus === 'pending');
  return <section className="provider-notice manuscript-analysis-progress" role="status">
    <div><strong>Manuskript-Analyse</strong><span>Phase: {phaseLabels[job.currentPhase]} · Kapitel {currentChapterNumber || '—'} von {chapters} · Prüfeinheit {currentChapter || job.completedUnits} von {job.totalUnits}</span><span>{job.completedUnits} abgeschlossen · {job.failedUnits} fehlgeschlagen · {units.filter((unit) => unit.status === 'pending').length} offen · Provider {job.providerId}</span>{Object.entries(job.phaseProgress).length > 0 && <div className="manuscript-analysis-phases">{(Object.entries(job.phaseProgress) as Array<[ManuscriptAnalysisPhase, NonNullable<ManuscriptAnalysisJob['phaseProgress'][ManuscriptAnalysisPhase]>]>).map(([phase, progress]) => <span key={phase}>{phaseLabels[phase]}: {progress.completedUnits}/{progress.totalUnits} · {progress.status}</span>)}</div>}{phaseResults.length > 0 && <div className="manuscript-analysis-phases"><strong>Jobgebundene Ergebnisse</strong>{phaseResults.map((result) => <span key={result.id}>{phaseLabels[result.phase]} · {result.resultKind} · {artifacts.filter((artifact) => artifact.phase === result.phase && artifact.reviewStatus === 'pending').length} offen</span>)}</div>}{failed && <span className="save-error">Fehler in Kapitel {failed.chapterId}{failed.pageNumber === undefined ? '' : ` · Seite ${failed.pageNumber}`} · {failed.errorCode ?? 'ANALYSIS_FAILED'} · Provider {failed.actualProvider ?? failed.requestedProvider ?? job.providerId} · {new Date(failed.updatedAt).toLocaleString('de-DE')}: {failed.errorMessage ?? 'Unbekannter Fehler'}</span>}{error && <span className="save-error">{error}</span>}</div>
    {job.status === 'awaiting_user_review' && <div className="manuscript-import-review"><strong>Zentrales Importreview</strong><span>{reviewable.length} offene Artefakte · {pendingDrafts.length} offene Draft-Zustände. Jede Entscheidung bleibt jobgebunden.</span>{reviewable.map((artifact) => <article className="structure-proposal" key={artifact.id}><div><strong>{artifact.artifactType}</strong><span>{artifact.phase}{artifact.unitId ? ` · Einheit ${artifact.unitId}` : ''}</span><p>Artefakt {artifact.artifactId}</p></div><div className="longform-actions">{onReviewArtifact && <><button className="ghost-button" onClick={() => void onReviewArtifact(artifact.id, 'confirmed')}>Bestätigen</button><button className="text-button" onClick={() => void onReviewArtifact(artifact.id, 'uncertain')}>Unsicher</button><button className="text-button" onClick={() => void onReviewArtifact(artifact.id, 'rejected')}>Ablehnen</button></>}</div></article>)}{pendingDrafts.map((entry) => <article className="structure-proposal" key={entry.id}><div><strong>Continuity State</strong><span>{entry.stateKind} · {entry.entityId}</span><p>{entry.previousState} → {entry.newState} · {entry.sourceExcerpt}</p></div><div className="longform-actions">{onReviewDraft && <><button className="ghost-button" onClick={() => void onReviewDraft(entry.id, 'confirmed')}>Bestätigen</button><button className="text-button" onClick={() => void onReviewDraft(entry.id, 'uncertain')}>Unsicher</button><button className="text-button" onClick={() => void onReviewDraft(entry.id, 'rejected')}>Ablehnen</button></>}</div></article>)}<div className="manuscript-analysis-report"><strong>Abschlussbericht-Vorschau</strong><span>Kapitel {chapters} · Prüfeinheiten {units.length} · Timeline/Graph-Artefakte {artifacts.filter((item) => item.artifactType === 'narrative_summary' || item.artifactType === 'plot_thread_proposal').length} · offene Entscheidungen {reviewable.length + pendingDrafts.length}</span></div></div>}
    {structureProposals.length > 0 && <div className="manuscript-structure-review"><strong>Strukturvorschau · semantische Szenenvorschläge</strong><span>Die Analyse schneidet den Text nicht automatisch. Prüfe jeden Vorschlag oder lasse das Kapitel implizit.</span>{structureProposals.map((proposal) => <article key={proposal.id} className="structure-proposal"><div><strong>{proposal.title}</strong><span>Position {proposal.startOffset}–{proposal.endOffset} · {Math.round(proposal.confidence * 100)} % Confidence</span><p>{proposal.boundaryReason}</p><blockquote>{proposal.evidenceExcerpt}</blockquote></div>{onReviewStructureProposal && <div className="longform-actions"><button className="ghost-button" onClick={() => void onReviewStructureProposal(proposal.id, 'accepted')}>Bestätigen</button><button className="text-button" onClick={() => void onReviewStructureProposal(proposal.id, 'uncertain')}>Unsicher</button><button className="text-button" onClick={() => void onReviewStructureProposal(proposal.id, 'rejected')}>Verwerfen</button></div>}</article>)}</div>}
    <div className="longform-actions"><button className="ghost-button" disabled={active || job.status === 'awaiting_user_review'} onClick={onResume}><Play size={14} /> Analyse fortsetzen</button><button className="ghost-button" disabled={job.failedUnits === 0 || active} onClick={onRetry}><RotateCcw size={14} /> Fehlgeschlagene erneut prüfen</button><button className="ghost-button" disabled={!active} onClick={onPause}><Pause size={14} /> Analyse pausieren</button><button className="text-button" disabled={job.status === 'cancelled' || job.status === 'completed'} onClick={onCancel}><Square size={14} /> Analyse abbrechen</button>{job.status === 'awaiting_user_review' && (!confirmSkip ? <button className="ghost-button" onClick={() => setConfirmSkip(true)}>Offene Ergebnisse überspringen</button> : <><span>Wirklich {pendingArtifacts.length + pendingDrafts.length} offene Ergebnisse überspringen?</span><button className="ghost-button" onClick={() => { setConfirmSkip(false); onCompleteReview(true); }}>Ja, auditieren und überspringen</button><button className="text-button" onClick={() => setConfirmSkip(false)}>Abbrechen</button></>)}</div>
  </section>;
}
