import type { Chapter, MindEdge, MindNode, Project, StoryEntity, TimelineEvent } from '../types/domain';

export const demoProject: Project = { id: 'project-zugestellt', title: 'Zugestellt', author: 'Mara König', description: 'Ein psychologischer Mystery-Roman über Erinnerung, Schuld und eine Paketnummer, die nicht existieren dürfte.', updatedAt: 'Heute, 09:42', wordCount: 18420, openWarnings: 3, bibleProgress: 72 };
export const demoChapters: Chapter[] = [
  { id: 'chapter-1', bookId: 'book-1', title: 'Kapitel 1 – Zugestellt', orderIndex: 1, scenes: [{ id: 'scene-1', chapterId: 'chapter-1', title: 'Die Zustellung', orderIndex: 1, content: 'Der Karton stand vor der Tür, als Marek nach Hause kam. Kein Klingeln. Keine Nachricht. Nur sein Name, sauber gedruckt, und eine Paketnummer, die er sofort erkannte.\n\nEr hob den Deckel nicht an. Noch nicht. Im Treppenhaus roch es nach nassem Stein und dem Parfüm der Nachbarin aus dem dritten Stock.', pov: 'Marek', location: 'Mareks Wohnung', storyTime: 'Montag, 18:40', status: 'revised', goal: 'Marek erhält den Gegenstand, den er längst vergessen wollte.', notes: 'Die Spannung entsteht aus dem Zögern vor dem Öffnen.' }] },
  { id: 'chapter-2', bookId: 'book-1', title: 'Kapitel 2 – Das Foto', orderIndex: 2, scenes: [{ id: 'scene-2', chapterId: 'chapter-2', title: 'Silbergelatine', orderIndex: 1, content: 'Auf dem Foto war die Wohnung leer. Nicht verlassen, sondern leer, als hätte jemand die Wände aus der Wirklichkeit geschnitten. Lena stand am Rand des Bildes und sah in eine Richtung, die Marek nicht sehen konnte.', pov: 'Marek', location: 'Küchentisch', storyTime: 'Dienstag, 08:15', status: 'draft', goal: 'Das Foto verbindet Lena mit der unmöglichen Paketnummer.', notes: 'Hinweis auf die Simulation nur über Bildfehler.' }] },
  { id: 'chapter-3', bookId: 'book-1', title: 'Kapitel 3 – Abweichung', orderIndex: 3, scenes: [{ id: 'scene-3', chapterId: 'chapter-3', title: 'Die zweite Nummer', orderIndex: 1, content: '„Du hast die Nummer geändert“, sagte Lena.\n\nMarek sah auf den Aufkleber. Die Zahlen waren dieselben wie gestern. Nur die letzte Stelle schien sich gegen das Licht zu wehren.\n\n„Ich weiß nicht, wovon du sprichst.“\n\nDas war die erste Lüge, die er ihr erzählte.', pov: 'Marek', location: 'Café Meridian', storyTime: 'Dienstag, 13:20', status: 'draft', goal: 'Marek wird mit einer Tatsache konfrontiert, die er noch nicht akzeptieren kann.', notes: 'Szene 2 aus dem Konzept: Marek weiß nach dieser Szene von der Änderung.' }] },
];
export const demoEntities: StoryEntity[] = [
  { id: 'entity-marek', projectId: demoProject.id, name: 'Marek', type: 'character', description: 'Vermeidet Entscheidungen, wenn sie eine alte Schuld sichtbar machen könnten. Beobachtet mehr, als er zugibt.', status: 'confirmed', confidence: 0.96, source: 'Band 1 · Kapitel 1', chapter: 'Kapitel 1', scene: 'Die Zustellung', authorConfirmed: true, updatedAt: 'Heute, 09:10', tags: ['Hauptfigur', 'POV'], origin: 'manual' },
  { id: 'entity-lena', projectId: demoProject.id, name: 'Lena', type: 'character', description: 'Kennt die Abweichung der Paketnummer und testet, wie weit Marek die gemeinsame Vergangenheit verdrängt.', status: 'confirmed', confidence: 0.91, source: 'Band 1 · Kapitel 3', chapter: 'Kapitel 3', scene: 'Die zweite Nummer', authorConfirmed: true, updatedAt: 'Gestern, 17:40', tags: ['Schlüsselrolle', 'Wissen'], origin: 'manual' },
  { id: 'entity-package', projectId: demoProject.id, name: 'Veränderte Paketnummer', type: 'clue', description: 'Die letzte Stelle verändert sich abhängig vom Blickwinkel. Sie ist ein Hinweis auf die Simulation.', status: 'proposed', confidence: 0.78, source: 'Band 1 · Kapitel 2', chapter: 'Kapitel 2', scene: 'Silbergelatine', authorConfirmed: false, updatedAt: 'Heute, 08:34', tags: ['Hinweis', 'Simulation'], origin: 'manual' },
  { id: 'entity-simulation', projectId: demoProject.id, name: 'Die Simulation', type: 'secret', description: 'Eine mögliche Erklärung für die widersprüchlichen Räume und Erinnerungen. Noch nicht als Kanon bestätigt.', status: 'uncertain', confidence: 0.64, source: 'Band 1 · Kapitel 2', chapter: 'Kapitel 2', scene: 'Silbergelatine', authorConfirmed: false, updatedAt: 'Heute, 08:34', tags: ['Geheimnis', 'Vermutung'], origin: 'manual' },
  { id: 'entity-meridian', projectId: demoProject.id, name: 'Café Meridian', type: 'place', description: 'Neutraler Treffpunkt zwischen Marek und Lena. Die Uhr geht sieben Minuten nach.', status: 'confirmed', confidence: 0.88, source: 'Band 1 · Kapitel 3', chapter: 'Kapitel 3', scene: 'Die zweite Nummer', authorConfirmed: true, updatedAt: 'Heute, 09:02', tags: ['Ort'], origin: 'manual' },
  { id: 'entity-thread', projectId: demoProject.id, name: 'Wer hat die Nummer verändert?', type: 'plot_thread', description: 'Offener Handlungsstrang. Marek muss entscheiden, ob er Lena glaubt, bevor die nächste Zustellung eintrifft.', status: 'proposed', confidence: 0.72, source: 'Autorennotiz', chapter: 'Kapitel 3', scene: 'Die zweite Nummer', authorConfirmed: false, updatedAt: 'Heute, 09:20', tags: ['Offen', 'Konflikt'], origin: 'manual' },
];
export const demoEvents: TimelineEvent[] = [
  { id: 'event-1', title: 'Das Paket wird zugestellt', storyTime: 'Mo · 18:40', chapter: 'Kapitel 1', scene: 'Die Zustellung', location: 'Mareks Wohnung', characters: ['Marek'], pov: 'Marek', summary: 'Marek findet einen Karton mit seinem Namen und einer vertrauten Paketnummer.', consequences: 'Er nimmt das Paket mit, öffnet es aber nicht.', knowledge: 'Marek weiß, dass die Nummer mit einem verdrängten Ereignis verbunden ist.', clue: 'Die Nummer ist drei Ziffern länger als üblich.', status: 'confirmed', track: 'Haupthandlung' },
  { id: 'event-2', title: 'Das Foto zeigt eine leere Wohnung', storyTime: 'Di · 08:15', chapter: 'Kapitel 2', scene: 'Silbergelatine', location: 'Küchentisch', characters: ['Marek', 'Lena'], pov: 'Marek', summary: 'Ein Foto widerspricht der Erinnerung an Mareks Wohnung.', consequences: 'Marek beginnt, seine Wahrnehmung zu protokollieren.', knowledge: 'Leserwissen: Im Bild fehlt eine Wand, die Marek berührt hat.', clue: 'Paketfoto', status: 'proposed', track: 'Leserwissen' },
  { id: 'event-3', title: 'Lena nennt die zweite Nummer', storyTime: 'Di · 13:20', chapter: 'Kapitel 3', scene: 'Die zweite Nummer', location: 'Café Meridian', characters: ['Marek', 'Lena'], pov: 'Marek', summary: 'Lena behauptet, Marek habe die letzte Stelle verändert.', consequences: 'Marek sagt seine erste bewusste Lüge zu Lena.', knowledge: 'Marek weiß jetzt, dass Lena die Abweichung ebenfalls sieht.', clue: 'Veränderte Paketnummer', status: 'confirmed', track: 'Marek' },
  { id: 'event-4', title: 'Die Uhr geht sieben Minuten nach', storyTime: 'Di · 13:27', chapter: 'Kapitel 3', scene: 'Die zweite Nummer', location: 'Café Meridian', characters: ['Marek', 'Lena'], pov: 'Lena', summary: 'Ein scheinbares Detail legt eine zweite Zeitspur an.', consequences: 'Lena beschließt, Marek noch nicht die Wahrheit zu sagen.', knowledge: 'Tatsächliche Wahrheit: Die Abweichung ist absichtlich erzeugt.', status: 'uncertain', track: 'Tatsächliche Wahrheit' },
];
export const mindNodes: MindNode[] = [
  { id: 'marek', label: 'Marek', type: 'Charakter', x: 80, y: 130, status: 'confirmed' }, { id: 'lena', label: 'Lena', type: 'Charakter', x: 80, y: 310, status: 'confirmed' }, { id: 'photo', label: 'Paketfoto', type: 'Hinweis', x: 350, y: 80, status: 'proposed' }, { id: 'number', label: 'Veränderte Paketnummer', type: 'Hinweis', x: 350, y: 250, status: 'proposed' }, { id: 'simulation', label: 'Simulation', type: 'Geheimnis', x: 650, y: 170, status: 'uncertain' }, { id: 'apartment', label: 'Wohnung', type: 'Ort', x: 350, y: 430, status: 'confirmed' }, { id: 'chapter3', label: 'Kapitel 3', type: 'Kapitel', x: 650, y: 380, status: 'confirmed' },
];
export const mindEdges: MindEdge[] = [
  { id: 'e1', source: 'marek', target: 'number', label: 'weiß von' }, { id: 'e2', source: 'lena', target: 'number', label: 'kennt' }, { id: 'e3', source: 'photo', target: 'simulation', label: 'ist Hinweis auf' }, { id: 'e4', source: 'number', target: 'simulation', label: 'widerspricht' }, { id: 'e5', source: 'photo', target: 'apartment', label: 'befindet sich in' }, { id: 'e6', source: 'number', target: 'chapter3', label: 'wird enthüllt in' },
];
