export type EntityStatus = 'confirmed' | 'proposed' | 'uncertain' | 'contradicted' | 'retconned' | 'archived';
export type EntityType = 'character' | 'relationship' | 'place' | 'organization' | 'world_rule' | 'object' | 'event' | 'fact' | 'clue' | 'secret' | 'plot_thread' | 'retcon' | 'author_note' | 'open_question';
export type AppView = 'dashboard' | 'editor' | 'bible' | 'timeline' | 'mindmap' | 'characters' | 'threads' | 'research' | 'files' | 'settings';
export type AiTaskType = 'chat' | 'bible_update' | 'consistency_check' | 'grammar_review' | 'manuscript_import' | 'deep_research' | 'timeline_validation' | 'character_analysis' | 'continuity_passage' | 'manuscript_structure';
export type CorrectionKind = 'spelling' | 'grammar' | 'punctuation' | 'capitalization' | 'whitespace';

export type SceneStatus = 'draft' | 'revised' | 'final';
export type ManuscriptFont = 'serif' | 'sans' | 'typewriter';
export interface EditorPreferences { fontFamily: ManuscriptFont; fontSize: number; lineHeight: number; }
export interface Project { id: string; title: string; author: string; description: string; updatedAt: string; createdAt?: string; wordCount: number; openWarnings: number; bibleProgress: number; status?: 'active' | 'archived'; lastOpenedAt?: string; }
export type ProjectOnboardingStep = 'project' | 'lore' | 'manuscript' | 'summary' | 'completed';
export interface ProjectOnboardingState { projectId: string; currentStep: ProjectOnboardingStep; completedSteps: string[]; skippedSteps: string[]; language: string; genre: string; loreCrafterRunId?: string; importId?: string; updatedAt: string; }
export type SaveProjectOnboardingStateInput = Omit<ProjectOnboardingState, 'updatedAt'>;
export type BookGenreSource = 'manual' | 'ai_detected' | 'imported';
export interface Book { id: string; projectId: string; title: string; volume: number; primaryGenreId?: string; secondaryGenreIds: string[]; customGenreNames: string[]; genreSource?: BookGenreSource; genreConfidence?: number; genreReason?: string; genreAuthorConfirmed: boolean; genreDetectedAt?: string; genreSupportingSignals?: string[]; genreContradictingSignals?: string[]; genreAlternatives?: Array<{ genreId?: string; customGenre?: string; reason?: string }>; genreAudienceNotes?: string[]; genreWarnings?: string[]; genrePromptVersion?: string; createdAt?: string; updatedAt?: string; }
export interface SaveBookGenresInput { bookId: string; projectId: string; primaryGenreId?: string; secondaryGenreIds: string[]; customGenreNames: string[]; genreSource?: BookGenreSource; genreConfidence?: number; genreReason?: string; genreAuthorConfirmed: boolean; genreDetectedAt?: string; genreSupportingSignals?: string[]; genreContradictingSignals?: string[]; genreAlternatives?: Array<{ genreId?: string; customGenre?: string; reason?: string }>; genreAudienceNotes?: string[]; genreWarnings?: string[]; genrePromptVersion?: string; analysisJobId?: string; providerId?: string; }
export interface Chapter { id: string; bookId: string; title: string; orderIndex: number; scenes: Scene[]; importVersionId?: string; importStatus?: 'active' | 'archived'; createdAt?: string; updatedAt?: string; }
export interface Scene { id: string; chapterId: string; title: string; orderIndex: number; content: string; pov: string; location: string; storyTime: string; status: SceneStatus; goal: string; notes: string; isImplicit?: boolean; createdAt?: string; updatedAt?: string; }
export type SceneVersionReason = 'manual' | 'before_correction' | 'before_ai_change' | 'before_import' | 'automatic_checkpoint';
export interface SceneVersion { id: string; sceneId: string; versionNumber: number; content: string; reason: SceneVersionReason; createdAt: string; scene: Scene; }
export type StoryEntityOrigin = 'manual' | 'bible_update' | 'edited' | 'lore_crafter';
export interface StoryEntity { id: string; projectId: string; name: string; type: EntityType; description: string; status: EntityStatus; confidence: number; source: string; chapter: string; scene: string; authorConfirmed: boolean; updatedAt: string; createdAt?: string; tags: string[]; origin: StoryEntityOrigin; }
export interface StorySourceReference { id: string; projectId: string; entityId?: string; proposalId?: string; chapterId?: string; sceneId?: string; sourceDocumentId?: string; excerpt: string; startOffset?: number; endOffset?: number; createdAt: string; }
export type ProjectSourceKind = 'lore_crafter' | 'research' | 'author_note' | 'external_text';
export interface ProjectSourceDocument { id: string; projectId: string; sourceKind: ProjectSourceKind; title: string; content: string; contentHash: string; originId?: string; createdAt: string; updatedAt: string; }
export interface CreateProjectSourceDocumentInput { projectId: string; sourceKind: ProjectSourceKind; title: string; content: string; contentHash: string; originId?: string; }
export interface CreateProjectSourceReferenceInput { projectId: string; sourceDocumentId: string; entityId?: string; proposalId?: string; excerpt: string; startOffset: number; endOffset: number; }
export type BibleRunStatus = 'pending' | 'running' | 'completed' | 'failed' | 'reviewed';
export type BibleProposalAction = 'create_entity' | 'update_entity' | 'add_source' | 'mark_contradiction' | 'create_open_question' | 'create_author_note';
export type BibleClassification = 'observable_fact' | 'interpretation' | 'open_question' | 'possible_contradiction' | 'author_note';
export type BibleReviewStatus = 'pending' | 'accepted' | 'edited' | 'rejected';
export interface BibleUpdateRun { id: string; projectId: string; sceneId: string; sceneUpdatedAt: string; contentHash: string; extractorId: string; analyzedContent?: string; status: BibleRunStatus; createdAt: string; completedAt?: string; errorMessage?: string; }
export interface BibleProposal { id: string; runId: string; projectId: string; sceneId: string; targetEntityId?: string; proposalAction: BibleProposalAction; entityType: EntityType; candidateName: string; candidateDescription: string; candidateStatus: EntityStatus; confidence: number; classification: BibleClassification; evidenceExcerpt: string; startOffset?: number; endOffset?: number; reason: string; reviewStatus: BibleReviewStatus; reviewedAt?: string; createdAt: string; }
export interface BibleProposalDraft { targetEntityId?: string; proposalAction: BibleProposalAction; entityType: EntityType; candidateName: string; candidateDescription: string; candidateStatus: EntityStatus; confidence: number; classification: BibleClassification; evidenceExcerpt: string; startOffset?: number; endOffset?: number; reason: string; }
export interface BibleExtractionInput { project: Project; chapter: Chapter; scene: Scene; existingEntities: StoryEntity[]; provisionalEntities?: ProvisionalEntity[]; provisionalAliases?: ProvisionalAlias[]; relevantSources?: StorySourceReference[]; previousAnalyzedContent?: string; changedRange?: { start: number; end: number }; }
export interface BibleExtractionResult { proposals: BibleProposalDraft[]; warnings: string[]; }
export interface BibleExtractor { readonly id: string; extract(input: BibleExtractionInput): Promise<BibleExtractionResult>; }
export interface ContextRequest { projectId: string; currentChapterId?: string; currentSceneId?: string; userQuestion: string; includeProposedSummaries?: boolean; passageText?: string; passageStartOffset?: number; passageEndOffset?: number; }
export type LoreCategory = 'world_rule' | 'history' | 'objective_truth' | 'belief' | 'myth' | 'mystery' | 'terminology';
export type LoreScope = 'series' | 'book' | 'arc';
export type LoreRevealState = 'author_only' | 'foreshadowed' | 'reader_revealed';
export type LoreImportance = 'core' | 'supporting' | 'background';
export type ProjectRuleScope = 'project' | 'book' | 'arc';
export type ProjectRuleStatus = 'proposed' | 'confirmed' | 'rejected' | 'retired';
export type ProjectRuleOrigin = 'manual' | 'bible_update' | 'edited' | 'lore_crafter';
export interface ProjectRule { id: string; projectId: string; title: string; statement: string; scope: ProjectRuleScope; prerequisites: string[]; effects: string[]; exceptions: string[]; connectedLoreIds: string[]; sourceReferenceIds: string[]; status: ProjectRuleStatus; confidence: number; authorConfirmed: boolean; origin: ProjectRuleOrigin; createdAt: string; updatedAt: string; }
export interface SaveProjectRuleInput extends Omit<ProjectRule, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export type ProjectRuleProposalReviewStatus = 'pending' | 'accepted' | 'edited' | 'rejected';
export interface ProjectRuleProposal { id: string; projectId: string; targetRuleId?: string; title: string; statement: string; scope: ProjectRuleScope; prerequisites: string[]; effects: string[]; exceptions: string[]; connectedLoreIds: string[]; sourceReferenceIds: string[]; evidenceExcerpt: string; chapterId?: string; sceneId?: string; startOffset?: number; endOffset?: number; confidence: number; reason: string; reviewStatus: ProjectRuleProposalReviewStatus; reviewedAt?: string; createdAt: string; }
export interface SaveProjectRuleProposalInput extends Omit<ProjectRuleProposal, 'id' | 'createdAt' | 'reviewedAt' | 'reviewStatus'> { id?: string; reviewStatus?: ProjectRuleProposalReviewStatus; }
export type ContinuityStateKind = 'item_existence' | 'item_availability' | 'ownership' | 'location' | 'physical_condition' | 'injury' | 'property' | 'knowledge' | 'relationship' | 'promise' | 'goal' | 'open_action';
export type ContinuityStateStatus = 'proposed' | 'confirmed' | 'uncertain' | 'contradicted' | 'rejected' | 'retconned';
export interface ManuscriptPosition { chapterId: string; sceneId: string; offset?: number; }
export interface ContinuityStateLedgerEntry { id: string; projectId: string; entityId: string; relatedEntityId?: string; stateKind: ContinuityStateKind; previousState: string; newState: string; reason?: string; evidenceExcerpt?: string; chapterId?: string; sceneId?: string; startOffset?: number; endOffset?: number; sourceReferenceId?: string; status: ContinuityStateStatus; confidence: number; authorConfirmed: boolean; createdAt: string; updatedAt: string; }
export interface SaveContinuityStateInput extends Omit<ContinuityStateLedgerEntry, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export type ContinuityReviewFindingType = 'critical_contradiction' | 'probable_contradiction' | 'missing_explanation' | 'character_deviation' | 'lore_compatible_anomaly' | 'possible_intentional_exception' | 'insufficient_evidence';
export type ContinuityReviewSeverity = 'info' | 'warning' | 'critical';
export type ContinuityReviewStatus = 'open' | 'accepted' | 'dismissed' | 'resolved' | 'deferred';
export type ContinuityFindingDecisionStatus = 'open' | 'resolved_after_text_change' | 'resolved_with_confirmed_rule' | 'accepted_exception' | 'deferred_rule_review' | 'deferred_canon_review' | 'deferred_open_question' | 'dismissed';
export type ContinuityFindingDecisionKind = 'text_correction' | 'confirmed_rule' | 'new_rule' | 'canon_review' | 'intentional_exception' | 'open_question' | 'dismiss';
export interface ContinuityFindingDecision { id: string; findingId: string; projectId: string; status: ContinuityFindingDecisionStatus; decisionKind: ContinuityFindingDecisionKind; ruleId?: string; ruleProposalId?: string; openQuestionEntityId?: string; sourceReferenceId?: string; exceptionReason?: string; contentHash?: string; payload?: Record<string, unknown>; createdAt: string; updatedAt: string; }
export interface ContinuityCanonChangeAudit { id: string; findingId: string; projectId: string; targetEntityId?: string; targetStateId?: string; action: 'previous_incomplete' | 'retcon' | 'new_information' | 'unreliable_perspective' | 'cancelled'; reason: string; previousSourceReferenceId?: string; newSourceReferenceId?: string; sourceReferenceIds: string[]; payload?: Record<string, unknown>; createdAt: string; }
export type ContinuityReviewSourceKind = 'word_threshold' | 'page_marker' | 'bible_update' | 'longform_section' | 'manual';
export interface ContinuityReviewSettings { projectId: string; wordThreshold: number; updatedAt: string; }
export type ContinuityReviewRunStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'reviewed';
export interface ContinuityReviewRun { id: string; projectId: string; chapterId?: string; sceneId?: string; sourceKind: ContinuityReviewSourceKind; contentHash: string; startOffset?: number; endOffset?: number; providerId: string; status: ContinuityReviewRunStatus; createdAt: string; completedAt?: string; errorMessage?: string; }
export interface ContinuityCounterEvidence { sourceReferenceId?: string; excerpt: string; chapterId?: string; sceneId?: string; startOffset?: number; endOffset?: number; }
export interface ContinuityReviewFinding { id: string; runId: string; projectId: string; chapterId?: string; sceneId?: string; findingType: ContinuityReviewFindingType; severity: ContinuityReviewSeverity; subjectEntityId?: string; relatedEntityIds: string[]; relatedStateIds: string[]; relatedRuleIds: string[]; objectiveConflict: string; loreExplanations: string[]; evidenceExcerpt: string; sourceReferenceId?: string; counterEvidenceExcerpts: string[]; counterEvidence?: ContinuityCounterEvidence[]; confidence: number; startOffset?: number; endOffset?: number; reason: string; reviewStatus: ContinuityReviewStatus; userDecision?: string; createdAt: string; updatedAt: string; }
export type PlotThreadLifecycleStatus = 'open' | 'closure_candidate' | 'partially_resolved' | 'resolved' | 'reopened' | 'abandoned';
export interface PlotThreadLifecycle { id: string; projectId: string; entityId: string; lifecycleStatus: PlotThreadLifecycleStatus; lastSourceReferenceId?: string; updatedAt: string; }
export interface PlotThreadLifecycleProposal { id: string; runId: string; projectId: string; entityId: string; proposedStatus: Exclude<PlotThreadLifecycleStatus, 'resolved'>; evidenceExcerpt: string; sourceReferenceId?: string; startOffset?: number; endOffset?: number; reason: string; confidence: number; reviewStatus: BibleReviewStatus; reviewedAt?: string; createdAt: string; }
export interface SaveContinuityReviewInput { projectId: string; chapterId?: string; sceneId?: string; sourceKind: ContinuityReviewSourceKind; contentHash: string; startOffset?: number; endOffset?: number; providerId?: string; }
export interface SaveContinuityReviewRunStatusInput { id: string; status: ContinuityReviewRunStatus; errorMessage?: string; completedAt?: string; }
export interface SaveContinuityFindingInput extends Omit<ContinuityReviewFinding, 'id' | 'createdAt' | 'updatedAt' | 'reviewStatus' | 'userDecision'> { id?: string; reviewStatus?: ContinuityReviewStatus; userDecision?: string; }
export interface ApplyContinuityFindingDecisionInput { findingId: string; projectId: string; status: ContinuityFindingDecisionStatus; decisionKind: ContinuityFindingDecisionKind; ruleId?: string; ruleProposalId?: string; openQuestionEntityId?: string; sourceReferenceId?: string; exceptionReason?: string; contentHash?: string; payload?: Record<string, unknown>; canonAction?: ContinuityCanonChangeAudit['action']; canonTargetEntityId?: string; canonTargetStateId?: string; canonReason?: string; canonSourceReferenceIds?: string[]; }
export interface ReconcileContinuityTextCorrectionInput { projectId: string; sceneId: string; runId: string; contentHash: string; findings: Array<{ findingType: ContinuityReviewFindingType; subjectEntityId?: string; objectiveConflict: string }>; }
export interface ContinuityObservedPassage { summary: string; evidenceExcerpt: string; entityIds: string[]; startOffset?: number; endOffset?: number; }
export interface ContinuityStateChangeProposal { entityId: string; relatedEntityId?: string; stateKind: ContinuityStateKind; previousState: string; newState: string; confidence: number; evidenceExcerpt: string; sourceReferenceId?: string; startOffset?: number; endOffset?: number; reason: string; }
export interface ContinuityContradictionProposal { findingType: Exclude<ContinuityReviewFindingType, 'character_deviation' | 'insufficient_evidence'>; subjectEntityId?: string; relatedEntityIds: string[]; relatedStateIds: string[]; objectiveConflict: string; evidenceExcerpt: string; sourceReferenceId?: string; counterEvidenceExcerpts: string[]; counterEvidence?: ContinuityCounterEvidence[]; confidence: number; startOffset?: number; endOffset?: number; reason: string; }
export interface ContinuityLoreMatch { ruleId: string; rationale: string; confidence: number; }
export interface ContinuityPlotThreadChangeProposal { entityId: string; proposedStatus: Exclude<PlotThreadLifecycleStatus, 'resolved'>; evidenceExcerpt: string; sourceReferenceId?: string; startOffset?: number; endOffset?: number; reason: string; confidence: number; }
export interface ContinuityAnalysisResult { observedActions: ContinuityObservedPassage[]; proposedStateChanges: ContinuityStateChangeProposal[]; objectiveContradictions: ContinuityContradictionProposal[]; missingExplanations: ContinuityContradictionProposal[]; matchedLoreRules: ContinuityLoreMatch[]; newRuleProposals: SaveProjectRuleProposalInput[]; plotThreadChanges: ContinuityPlotThreadChangeProposal[]; confidence: number; evidence: ChatSource[]; warnings: string[]; }
export type ManuscriptAnalysisPhase = 'structure' | 'passage_continuity' | 'bible_extraction' | 'character_memory' | 'scene_or_chapter_synthesis' | 'narrative_summaries' | 'plot_thread_synthesis' | 'book_end_state' | 'global_countercheck' | 'user_review' | 'completed';
export type StructureTransitionType = 'location_change' | 'time_jump' | 'pov_change' | 'character_group_change' | 'flashback_start' | 'flashback_end' | 'dream_start' | 'dream_end' | 'action_break' | 'narrative_transition' | 'chapter_continuation';
export type ManuscriptStructureReviewStatus = 'proposed' | 'accepted' | 'edited' | 'rejected' | 'uncertain';
export interface ManuscriptStructureProposal { id: string; runId: string; projectId: string; chapterId: string; temporaryId: string; startOffset: number; endOffset: number; title: string; povCharacterName?: string; povEntityId?: string; location: string; storyTime: string; participatingCharacterNames: string[]; goal: string; conflict: string; importantEvents: string[]; transitionType: StructureTransitionType; boundaryReason: string; confidence: number; evidenceExcerpt: string; reviewStatus: ManuscriptStructureReviewStatus; manualChanges?: Record<string, unknown>; createdAt: string; updatedAt: string; }
export interface ManuscriptStructureRun { id: string; projectId: string; chapterId: string; contentHash: string; providerId: string; promptVersion: string; status: 'pending' | 'running' | 'completed' | 'failed' | 'reviewed'; errorMessage?: string; createdAt: string; updatedAt: string; }
export interface ManuscriptStructureInput { projectId: string; chapter: Chapter; pageMarkers: ManuscriptAnalysisPageMarker[]; localHints: Array<{ startOffset: number; endOffset: number; reason: string }>; confirmedLore?: LoreMetadata[]; confirmedRules?: ProjectRule[]; }
export interface ManuscriptStructureResult { scenes: Array<Omit<ManuscriptStructureProposal, 'id' | 'runId' | 'projectId' | 'reviewStatus' | 'createdAt' | 'updatedAt'>>; warnings: string[]; }
export interface CreateManuscriptStructureRunInput { projectId: string; chapterId: string; contentHash: string; providerId: string; promptVersion: string; }
export interface SaveManuscriptStructureProposalInput extends Omit<ManuscriptStructureProposal, 'id' | 'createdAt' | 'updatedAt' | 'reviewStatus'> { id?: string; reviewStatus?: ManuscriptStructureReviewStatus; }
export type ProvisionalEntityType = 'character' | 'place' | 'organization' | 'object' | 'event' | 'fact' | 'clue' | 'secret' | 'plot_thread' | 'open_question' | 'world_rule_candidate' | 'author_note';
export type ProvisionalReviewStatus = 'proposed' | 'accepted' | 'rejected' | 'uncertain' | 'merged';
export interface ProvisionalEntity { id: string; jobId: string; projectId: string; entityType: ProvisionalEntityType; canonicalName: string; aliases: string[]; description: string; firstSourceReferenceId?: string; lastSourceReferenceId?: string; confidence: number; reviewStatus: ProvisionalReviewStatus; existingEntityId?: string; createdAt: string; updatedAt: string; }
export interface ProvisionalEntityMention { id: string; jobId: string; projectId: string; passageUnitId: string; chapterId: string; sceneId: string; startOffset: number; endOffset: number; excerpt: string; mentionText: string; resolvedProvisionalEntityId?: string; canonicalEntityId?: string; alternativeEntityIds: string[]; confidence: number; resolutionReason: string; createdAt: string; }
export interface ProvisionalAlias { id: string; provisionalEntityId: string; alias: string; sourceReferenceId?: string; confidence: number; reviewStatus: Exclude<ProvisionalReviewStatus, 'merged'>; createdAt: string; }
export interface ProvisionalRelation { id: string; jobId: string; projectId: string; sourceProvisionalEntityId: string; targetProvisionalEntityId: string; canonicalSourceEntityId?: string; canonicalTargetEntityId?: string; relationType: string; label: string; confidence: number; reviewStatus: Exclude<ProvisionalReviewStatus, 'merged'>; sourceReferenceId?: string; createdAt: string; updatedAt: string; }
export interface ProvisionalMergeProposal { id: string; jobId: string; projectId: string; leftProvisionalEntityId: string; rightProvisionalEntityId?: string; existingEntityId?: string; reason: string; confidence: number; reviewStatus: ProvisionalReviewStatus; createdAt: string; }
export interface ProvisionalEvent { id: string; jobId: string; projectId: string; passageUnitId: string; chapterId: string; sceneId: string; title: string; summary: string; participantEntityIds: string[]; canonicalParticipantEntityIds?: string[]; startOffset: number; endOffset: number; confidence: number; reviewStatus: Exclude<ProvisionalReviewStatus, 'merged'>; sourceReferenceId?: string; createdAt: string; }
export interface SaveProvisionalRelationInput extends Omit<ProvisionalRelation, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface SaveProvisionalEventInput extends Omit<ProvisionalEvent, 'id' | 'createdAt'> { id?: string; }
export interface SaveProvisionalEntityInput extends Omit<ProvisionalEntity, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface SaveProvisionalMentionInput extends Omit<ProvisionalEntityMention, 'id' | 'createdAt'> { id?: string; }
export interface SaveProvisionalMergeProposalInput extends Omit<ProvisionalMergeProposal, 'id' | 'createdAt'> { id?: string; }
export interface MaterializeProvisionalEntityInput { projectId: string; jobId: string; provisionalEntityId: string; existingEntityId?: string; decision: 'accept' | 'merge'; }
export interface ManuscriptEntityResolutionInput { projectId: string; jobId: string; unit: ManuscriptAnalysisUnit; passageText: string; previousContext: string; confirmedEntities: StoryEntity[]; previousProvisionalEntities: ProvisionalEntity[]; previousAliases: ProvisionalAlias[]; }
export interface ManuscriptEntityResolutionResult { entities: Array<{ temporaryId: string; entityType: ProvisionalEntityType; canonicalName: string; aliases: string[]; description: string; confidence: number; existingEntityId?: string }>; mentions: Array<{ mentionText: string; startOffset: number; endOffset: number; temporaryEntityId?: string; alternativeTemporaryIds: string[]; confidence: number; resolutionReason: string; excerpt: string }>; relations: Array<{ sourceTemporaryId: string; targetTemporaryId: string; relationType: string; label: string; confidence: number }>; events: Array<{ title: string; summary: string; participantTemporaryIds: string[]; startOffset: number; endOffset: number; confidence: number; excerpt: string }>; mergeProposals: Array<{ leftTemporaryId: string; rightTemporaryId?: string; existingEntityId?: string; reason: string; confidence: number }>; warnings: string[]; }
export type ManuscriptAnalysisPhaseStatus = 'pending' | 'running' | 'paused' | 'completed' | 'failed' | 'cancelled';
export interface ManuscriptAnalysisPhaseProgress { status: ManuscriptAnalysisPhaseStatus; totalUnits: number; completedUnits: number; failedUnits: number; requestedProvider: string; actualProvider?: string; inputHash?: string; outputHash?: string; lastSuccessfulUnitId?: string; errorCode?: string; errorMessage?: string; updatedAt: string; }
export type ManuscriptAnalysisJobStatus = 'pending' | 'running' | 'paused' | 'awaiting_structure_review' | 'awaiting_user_review' | 'failed' | 'cancelled' | 'completed';
export interface ManuscriptAnalysisPageMarker { chapterId: string; pageNumber: number; label: string; sourceOffset: number; textOffset: number; }
export interface ManuscriptAnalysisJob { id: string; projectId: string; bookId: string; importReference: string; status: ManuscriptAnalysisJobStatus; currentPhase: ManuscriptAnalysisPhase; phaseProgress: Partial<Record<ManuscriptAnalysisPhase, ManuscriptAnalysisPhaseProgress>>; phaseErrors: Partial<Record<ManuscriptAnalysisPhase, { code: string; message: string; unitId?: string; at: string }>>; totalUnits: number; completedUnits: number; failedUnits: number; currentUnitId?: string; lastSuccessfulUnitId?: string; providerId: string; pageMarkers: ManuscriptAnalysisPageMarker[]; importVersionId?: string; createdAt: string; updatedAt: string; completedAt?: string; errorMessage?: string; }
export type ManuscriptAnalysisUnitStatus = 'pending' | 'running' | 'completed' | 'failed' | 'stale' | 'skipped';
export interface ManuscriptAnalysisUnit { id: string; jobId: string; projectId: string; chapterId: string; sceneId: string; orderIndex: number; pageNumber?: number; startOffset: number; endOffset: number; content: string; contentHash: string; status: ManuscriptAnalysisUnitStatus; retryCount: number; continuityRunId?: string; requestedProvider?: string; actualProvider?: string; promptVersion?: string; inputHash?: string; outputHash?: string; errorCode?: string; errorMessage?: string; createdAt: string; updatedAt: string; completedAt?: string; }
export interface CreateManuscriptAnalysisJobInput { projectId: string; bookId: string; importReference: string; providerId: string; pageMarkers?: ManuscriptAnalysisPageMarker[]; units: Array<{ id?: string; chapterId: string; sceneId: string; orderIndex: number; pageNumber?: number; startOffset: number; endOffset: number; content: string; contentHash: string; }>; newVersion?: boolean; }
export interface UpdateManuscriptAnalysisJobInput { id: string; status: ManuscriptAnalysisJobStatus; currentPhase?: ManuscriptAnalysisPhase; phaseProgress?: Partial<Record<ManuscriptAnalysisPhase, ManuscriptAnalysisPhaseProgress>>; phaseErrors?: Partial<Record<ManuscriptAnalysisPhase, { code: string; message: string; unitId?: string; at: string }>>; currentUnitId?: string; lastSuccessfulUnitId?: string; errorMessage?: string; completedAt?: string; }
export interface UpdateManuscriptAnalysisUnitInput { id: string; status: ManuscriptAnalysisUnitStatus; retryCount?: number; continuityRunId?: string; requestedProvider?: string; actualProvider?: string; promptVersion?: string; inputHash?: string; outputHash?: string; errorCode?: string; content?: string; contentHash?: string; errorMessage?: string; completedAt?: string; }
export interface ManuscriptSynthesisResult { summary: string; importantEvents: string[]; knowledgeChanges: string[]; relationshipChanges: string[]; openThreads: string[]; characterEndStates: string[]; objectEndStates: string[]; injuries: string[]; unresolvedClues: string[]; plotThreadStatuses: string[]; storyDirection: string; warnings: string[]; }
export interface DetectBookGenreInput { projectId: string; bookId: string; chapterSummaries: NarrativeSummary[]; entities: StoryEntity[]; plotThreads: PlotThreadLifecycleProposal[]; confirmedRules: ProjectRule[]; timelineEvents: PersistentTimelineEvent[]; bookSynthesis?: ManuscriptSynthesisResult; projectStyle?: ProjectStyle; catalog?: Array<{ id: string; name: string; englishName?: string; category: string; description: string; searchTerms: string[]; active: boolean }>; }
export interface DetectBookGenreResult { primaryGenreId?: string; customPrimaryGenre?: string; secondaryGenreIds: string[]; customSecondaryGenres: string[]; confidence: number; reasoning: string; supportingSignals: string[]; contradictingSignals: string[]; alternativeGenres: Array<{ genreId?: string; customGenre?: string; reason: string }>; audienceNotes: string[]; warnings: string[]; }
export interface ManuscriptPhaseInput { projectId: string; bookId: string; chapters: Array<{ id: string; title: string; orderIndex: number; text: string }>; chapterSummaries: NarrativeSummary[]; confirmedEntities: StoryEntity[]; confirmedRules: ProjectRule[]; confirmedStates: ContinuityStateLedgerEntry[]; proposedFindings: ContinuityReviewFinding[]; proposedThreads: PlotThreadLifecycleProposal[]; contentHash: string; contextLevel?: 'hierarchical'; sceneContexts?: Array<{ id: string; chapterId: string; orderIndex: number; title: string; summary?: string; sourceReferenceIds: string[] }>; sourceReferences?: StorySourceReference[]; draftLedger?: ManuscriptAnalysisDraftLedgerEntry[]; timelineEvents?: PersistentTimelineEvent[]; budgetWarnings?: string[]; budget?: { maxCodePoints: number; includedCodePoints: number; truncatedSections: string[] }; }
export interface PlotThreadSynthesisResult { summary: string; openQuestions: string[]; threadGoals: string[]; developments: string[]; closureCandidates: string[]; partiallyResolved: string[]; reopened: string[]; threadProposals?: Array<{ entityId: string; proposedStatus: Exclude<PlotThreadLifecycleStatus, 'resolved'>; evidenceExcerpt: string; reason: string; confidence: number; sourceReferenceId?: string }>; warnings: string[]; }
export interface BookEndStateResult { summary: string; characterEndStates: string[]; knowledgeStates: string[]; falseBeliefs: string[]; relationships: string[]; objectOwners: string[]; injuries: string[]; locations: string[]; openActions: string[]; unresolvedThreads: string[]; endStateProposals?: Array<{ category: string; entityId?: string; statement: string; confidence: number; evidenceExcerpt?: string; sourceReferenceId?: string }>; warnings: string[]; }
export interface GlobalCountercheckResult { summary: string; contradictoryFacts: string[]; prematureKnowledge: string[]; lostOrDestroyedObjects: string[]; timeAndLocationConflicts: string[]; contradictoryRules: string[]; unclearExceptions: string[]; uncertainSources: string[]; countercheckFindings?: Array<{ severity: ContinuityReviewSeverity; category: string; objectiveConflict: string; reason: string; confidence: number; evidenceExcerpt?: string; sourceReferenceId?: string }>; warnings: string[]; }
export type ManuscriptAnalysisDraftLedgerStatus = 'proposed' | 'confirmed' | 'rejected' | 'uncertain' | 'superseded';
export interface ManuscriptAnalysisDraftLedgerEntry { id: string; jobId: string; unitId: string; projectId: string; entityId: string; relatedEntityId?: string; stateKind: ContinuityStateKind; previousState: string; newState: string; chapterId: string; sceneId: string; startOffset?: number; endOffset?: number; sourceExcerpt?: string; sourceReferenceId?: string; confidence: number; status: ManuscriptAnalysisDraftLedgerStatus; createdAt: string; updatedAt: string; }
export interface SaveManuscriptAnalysisDraftLedgerInput extends Omit<ManuscriptAnalysisDraftLedgerEntry, 'id' | 'createdAt' | 'updatedAt' | 'status'> { id?: string; status?: ManuscriptAnalysisDraftLedgerStatus; }
export interface SavePlotThreadLifecycleInput extends Omit<PlotThreadLifecycle, 'id' | 'updatedAt'> { id?: string; }
export interface SavePlotThreadLifecycleProposalInput extends Omit<PlotThreadLifecycleProposal, 'id' | 'createdAt' | 'reviewedAt' | 'reviewStatus'> { id?: string; reviewStatus?: BibleReviewStatus; }
export interface ProjectContext { projectId: string; currentScene?: Scene; currentChapter?: Chapter; relevantEntities: StoryEntity[]; relevantSources: StorySourceReference[]; openPlotThreads: StoryEntity[]; possibleContradictions: StoryEntity[]; lore?: LoreMetadata[]; projectRules?: ProjectRule[]; entityRelations?: StoryEntityRelation[]; continuityStates?: ContinuityStateLedgerEntry[]; characterProfiles?: CharacterProfile[]; characterStates?: CharacterSceneState[]; characterVoicePatterns?: CharacterVoicePattern[]; characterExperiences?: CharacterExperience[]; characterDialogueMemories?: CharacterDialogueMemory[]; relationshipMemories?: RelationshipMemory[]; characterKnowledgeStates?: CharacterKnowledgeState[]; projectStyle?: ProjectStyle; styleReferences?: StyleReference[]; acceptedStyleObservations?: ProjectStyleObservation[]; narrativeSummaries?: NarrativeSummary[]; }
export interface LoreMetadata { entityId: string; projectId: string; category: LoreCategory; scope: LoreScope; revealState: LoreRevealState; importance: LoreImportance; truthStatement: string; rulesText: string; exceptionsText: string; authorKnowledge: string; readerKnowledge: string; revealPlan: string; createdAt: string; updatedAt: string; }
export interface CharacterProfile { entityId: string; projectId: string; coreWant: string; coreNeed: string; fears: string; falseBelief: string; values: string; strengths: string; flaws: string; pressureBehavior: string; voice: string; backstory: string; arcSummary: string; createdAt: string; updatedAt: string; }
export interface CharacterSceneState { id: string; projectId: string; characterEntityId: string; sceneId: string; emotionalState: string; physicalState: string; goal: string; conflict: string; knowledgeNotes: string; relationshipState: string; changeNote: string; createdAt: string; updatedAt: string; }
export type CharacterMemoryStatus = 'proposed' | 'confirmed' | 'uncertain' | 'rejected' | 'retired' | 'retconned';
export type CharacterVoicePatternType = 'signature_word' | 'signature_phrase' | 'filler_word' | 'nickname' | 'address_pattern' | 'sentence_pattern' | 'humor_pattern' | 'metaphor_pattern' | 'avoidance_pattern' | 'lie_pattern' | 'stress_pattern' | 'relationship_specific_voice' | 'dialogue_rule';
export type CharacterExperienceSignificance = 'minor' | 'supporting' | 'major' | 'defining';
export type CharacterMemorySignificance = 'minor' | 'supporting' | 'important' | 'core';
export type CharacterMemoryReliability = 'reliable' | 'uncertain' | 'distorted' | 'implanted' | 'forgotten';
export type CharacterDialogueKind = 'statement' | 'promise' | 'threat' | 'lie' | 'confession' | 'reveal' | 'argument' | 'inside_joke' | 'nickname' | 'secret_shared' | 'secret_hidden' | 'boundary' | 'callback' | 'question' | 'accusation' | 'apology';
export type DialogueTruthfulness = 'true' | 'false' | 'partially_true' | 'speaker_believes_true' | 'unknown';
export type RelationshipMemoryType = 'inside_joke' | 'nickname' | 'shared_memory' | 'shared_secret' | 'promise' | 'betrayal' | 'argument' | 'trust_gain' | 'trust_loss' | 'relationship_shift' | 'debt' | 'favor' | 'fear' | 'attraction' | 'resentment' | 'callback' | 'boundary';
export type CharacterKnowledgeKind = 'knows' | 'suspects' | 'believes_false' | 'denies' | 'forgot' | 'unknown';
export type CharacterMemoryKind = 'voice_pattern' | 'experience' | 'dialogue_memory' | 'relationship_memory' | 'knowledge_state' | 'profile_observation';
export type CharacterMemoryClassification = 'observable' | 'interpretation' | 'author_decision_required' | 'possible_contradiction';
export type CharacterMemoryProposalKind = 'voice_pattern' | 'experience' | 'dialogue_memory' | 'relationship_memory' | 'knowledge_change' | 'profile_observation' | 'character_relation';
export type MemoryEvidenceRole = 'primary' | 'supporting' | 'contradicting';
export type DialogueParticipantRole = 'speaker' | 'listener' | 'present' | 'mentioned';
export interface CharacterVoicePattern { id: string; projectId: string; characterId: string; relatedCharacterId?: string; patternType: CharacterVoicePatternType; patternText: string; description: string; contextCondition: string; confidence: number; status: CharacterMemoryStatus; authorConfirmed: boolean; occurrenceCount: number; firstObservedSceneId?: string; lastObservedSceneId?: string; retiredSceneId?: string; sourceReferenceIds?: string[]; createdAt: string; updatedAt: string; }
export interface CharacterExperience { id: string; projectId: string; characterId: string; eventEntityId?: string; sceneId?: string; title: string; objectiveSummary: string; subjectiveInterpretation: string; emotionalImpact: string; lastingEffect: string; significance: CharacterExperienceSignificance; memoryReliability: CharacterMemoryReliability; status: CharacterMemoryStatus; authorConfirmed: boolean; sourceReferenceIds?: string[]; createdAt: string; updatedAt: string; }
export interface DialogueMemoryParticipant { dialogueMemoryId: string; characterId: string; role: DialogueParticipantRole; }
export interface CharacterDialogueMemory { id: string; projectId: string; speakerId: string; sceneId: string; dialogueKind: CharacterDialogueKind; topic: string; summary: string; exactExcerpt: string; emotionalTone: string; hiddenIntent: string; significance: CharacterMemorySignificance; truthfulness: DialogueTruthfulness; status: CharacterMemoryStatus; authorConfirmed: boolean; participants: DialogueMemoryParticipant[]; sourceReferenceIds?: string[]; createdAt: string; updatedAt: string; }
export interface RelationshipMemory { id: string; projectId: string; characterAId: string; characterBId: string; sceneId?: string; memoryType: RelationshipMemoryType; title: string; summary: string; privateMeaning: string; relationshipEffect: string; significance: CharacterMemorySignificance; status: CharacterMemoryStatus; authorConfirmed: boolean; sourceReferenceIds?: string[]; createdAt: string; updatedAt: string; }
export interface CharacterKnowledgeState { id: string; projectId: string; characterId: string; factEntityId: string; knowledgeState: CharacterKnowledgeKind; acquiredSceneId?: string; changedSceneId?: string; effectiveFromSceneId?: string; effectiveUntilSceneId?: string; sourceCharacterId?: string; certainty: number; notes: string; status: CharacterMemoryStatus; authorConfirmed: boolean; createdAt: string; updatedAt: string; }
export interface CharacterMemoryEvidence { id: string; projectId: string; memoryKind: CharacterMemoryKind; memoryId: string; sourceReferenceId: string; evidenceRole: MemoryEvidenceRole; createdAt: string; }
export interface CharacterMemoryUpdateRun { id: string; projectId: string; sceneId: string; contentHash: string; extractorId: string; manuscriptJobId?: string; analyzedContent?: string; status: BibleRunStatus; createdAt: string; completedAt?: string; errorMessage?: string; }
export interface VoicePatternProposalPayload { patternType: CharacterVoicePatternType; patternText: string; description: string; contextCondition: string; relatedCharacterId?: string; }
export interface ExperienceProposalPayload { title: string; objectiveSummary: string; subjectiveInterpretation: string; emotionalImpact: string; lastingEffect: string; significance: CharacterExperienceSignificance; memoryReliability: CharacterMemoryReliability; eventEntityId?: string; }
export interface DialogueMemoryProposalPayload { dialogueKind: CharacterDialogueKind; topic: string; summary: string; exactExcerpt: string; emotionalTone: string; hiddenIntent: string; significance: CharacterMemorySignificance; truthfulness: DialogueTruthfulness; participants: Array<{ characterId: string; role: DialogueParticipantRole }>; }
export interface RelationshipMemoryProposalPayload { relatedCharacterId: string; memoryType: RelationshipMemoryType; title: string; summary: string; privateMeaning: string; relationshipEffect: string; significance: CharacterMemorySignificance; }
export interface KnowledgeChangeProposalPayload { factEntityId: string; knowledgeState: CharacterKnowledgeKind; certainty: number; sourceCharacterId?: string; notes: string; }
export interface ProfileObservationProposalPayload { field: string; observedBehavior: string; possibleInterpretation: string; }
export interface CharacterRelationProposalPayload { relationType: StoryEntityRelationType; label: string; }
export type CharacterMemoryPayload = VoicePatternProposalPayload | ExperienceProposalPayload | DialogueMemoryProposalPayload | RelationshipMemoryProposalPayload | KnowledgeChangeProposalPayload | ProfileObservationProposalPayload | CharacterRelationProposalPayload;
export interface CharacterMemoryProposal { id: string; runId: string; projectId: string; sceneId: string; proposalKind: CharacterMemoryProposalKind; subjectCharacterId?: string; relatedCharacterId?: string; targetEntityId?: string; payload: CharacterMemoryPayload; classification: CharacterMemoryClassification; confidence: number; evidenceExcerpt: string; startOffset?: number; endOffset?: number; reason: string; reviewStatus: BibleReviewStatus; reviewedAt?: string; analyzedContentHash?: string; acceptedMemoryId?: string; acceptedMemoryKind?: CharacterMemoryKind; createdAt: string; }
export interface CharacterMemoryProposalDraft { proposalKind: CharacterMemoryProposalKind; subjectCharacterId?: string; relatedCharacterId?: string; targetEntityId?: string; payload: CharacterMemoryPayload; classification: CharacterMemoryClassification; confidence: number; evidenceExcerpt: string; startOffset?: number; endOffset?: number; reason: string; }
export interface CharacterMemoryExtractionInput { project: Project; chapter: Chapter; scene: Scene; characters: StoryEntity[]; existingEntities: StoryEntity[]; provisionalEntities?: ProvisionalEntity[]; provisionalAliases?: ProvisionalAlias[]; context: ProjectContext; changedRange?: { start: number; end: number }; }
export interface CharacterMemoryExtractionResult { proposals: CharacterMemoryProposalDraft[]; warnings: string[]; }
export interface SaveCharacterVoicePatternInput extends Omit<CharacterVoicePattern, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface SaveCharacterExperienceInput extends Omit<CharacterExperience, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface SaveCharacterDialogueMemoryInput extends Omit<CharacterDialogueMemory, 'id' | 'createdAt' | 'updatedAt' | 'participants'> { id?: string; participants: Omit<DialogueMemoryParticipant, 'dialogueMemoryId'>[]; }
export type SaveRelationshipMemoryInput = Omit<RelationshipMemory, 'id' | 'createdAt' | 'updatedAt'> & { id?: string; };
export interface SaveCharacterKnowledgeStateInput extends Omit<CharacterKnowledgeState, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface AddCharacterMemoryEvidenceInput { projectId: string; memoryKind: CharacterMemoryKind; memoryId: string; sourceReferenceId: string; evidenceRole: MemoryEvidenceRole; }
export interface CreateCharacterMemoryUpdateRunInput { projectId: string; sceneId: string; contentHash: string; extractorId: string; manuscriptJobId?: string; analyzedContent?: string; }
export interface ReviewCharacterMemoryProposalInput { proposalId: string; reviewStatus: Exclude<BibleReviewStatus, 'pending'>; decision?: 'accept' | 'uncertain' | 'reject'; payload?: CharacterMemoryPayload; }
export type StoryEntityRelationType = 'affects' | 'explains' | 'contradicts' | 'reveals' | 'hides' | 'depends_on' | 'applies_to' | 'caused_by' | 'connected_to';
export interface StoryEntityRelation { id: string; projectId: string; sourceEntityId: string; targetEntityId: string; relationType: StoryEntityRelationType; label: string; authorConfirmed: boolean; createdAt: string; updatedAt: string; }
export interface ProjectStyle { projectId: string; narrativePov: string; tense: string; sentenceStyle: string; dialogueStyle: string; descriptionDensity: string; innerMonologue: string; preferredPatterns: string[]; avoidedPatterns: string[]; notes: string; createdAt: string; updatedAt: string; }
export type ProjectStyleAnalysisStatus = 'pending' | 'running' | 'completed' | 'failed';
export interface ProjectStyleAnalysisRun { id: string; projectId: string; sourceHash: string; providerId: string; status: ProjectStyleAnalysisStatus; createdAt: string; completedAt?: string; errorMessage?: string; }
export type ProjectStyleObservationType = 'narrative_pov' | 'tense' | 'sentence_rhythm' | 'dialogue' | 'description' | 'inner_monologue' | 'humor' | 'pacing' | 'vocabulary' | 'transitions' | 'tension' | 'avoidance' | 'character_voice_separation';
export type ProjectStyleObservationReviewStatus = 'pending' | 'accepted' | 'edited' | 'rejected';
export interface ProjectStyleObservationEvidence { sourceId?: string; styleReferenceId?: string; excerpt?: string; }
export interface ProjectStyleObservation { id: string; runId: string; projectId: string; observationType: ProjectStyleObservationType; observationText: string; recommendation: string; confidence: number; evidence: ProjectStyleObservationEvidence[]; reviewStatus: ProjectStyleObservationReviewStatus; reviewedAt?: string; createdAt: string; }
export interface ProjectStyleAnalysisDraft { observationType: ProjectStyleObservationType; observationText: string; recommendation: string; confidence: number; evidence: string[]; }
export interface ProjectStyleAnalysisResult { observations: ProjectStyleAnalysisDraft[]; overallSummary: string; warnings: string[]; }
export interface NarrativeSummaryAnalysisResult { summary: string; importantEvents: string[]; openThreads: string[]; characterChanges: string[]; knowledgeChanges: string[]; relationshipEffects: string[]; warnings: string[]; }
export interface CreateProjectStyleAnalysisRunInput { projectId: string; sourceHash: string; providerId: string; }
export interface SaveProjectStyleObservationInput { runId: string; projectId: string; observationType: ProjectStyleObservationType; observationText: string; recommendation: string; confidence: number; evidence: ProjectStyleObservationEvidence[]; reviewStatus?: ProjectStyleObservationReviewStatus; }
export type SaveLoreMetadataInput = Omit<LoreMetadata, 'createdAt' | 'updatedAt'>;
export type SaveCharacterProfileInput = Omit<CharacterProfile, 'createdAt' | 'updatedAt'>;
export interface SaveCharacterSceneStateInput extends Omit<CharacterSceneState, 'id' | 'createdAt' | 'updatedAt'> { id?: string }
export type SaveProjectStyleInput = Omit<ProjectStyle, 'createdAt' | 'updatedAt'>;
export interface NarrativeSummary { id: string; projectId: string; scopeType: 'scene' | 'chapter' | 'book' | 'project'; scopeId: string; contentHash: string; summary: string; importantEvents: string[]; openThreads: string[]; characterChanges: string[]; status: 'proposed' | 'confirmed' | 'outdated' | 'rejected'; authorConfirmed: boolean; createdAt: string; updatedAt: string; }
export type SaveNarrativeSummaryInput = Omit<NarrativeSummary, 'id' | 'createdAt' | 'updatedAt'>;
export type StyleReferenceCategory = 'general' | 'dialogue' | 'tension' | 'description' | 'inner_monologue' | 'humor';
export interface StyleReference { id: string; projectId: string; chapterId?: string; sceneId: string; startOffset?: number; endOffset?: number; category: StyleReferenceCategory; label: string; excerpt: string; notes: string; weight: number; createdAt: string; updatedAt: string; }
export type CreateStyleReferenceInput = Omit<StyleReference, 'id' | 'createdAt' | 'updatedAt'>;
export interface UpdateStyleReferenceInput { id: string; projectId: string; label: string; category: StyleReferenceCategory; notes: string; weight: number; }
export interface CreateStoryEntityRelationInput { projectId: string; sourceEntityId: string; targetEntityId: string; relationType: StoryEntityRelationType; label: string; authorConfirmed: boolean; }
export interface CreateLoreEntryInput { projectId: string; name: string; entityType: Extract<EntityType, 'world_rule' | 'fact' | 'event' | 'secret' | 'clue' | 'organization' | 'place' | 'object' | 'plot_thread' | 'author_note'>; description: string; status: EntityStatus; category: LoreCategory; scope: LoreScope; revealState: LoreRevealState; importance: LoreImportance; truthStatement: string; rulesText: string; exceptionsText: string; authorKnowledge: string; readerKnowledge: string; revealPlan: string; tags: string[]; }
export interface LoreEntry { entity: StoryEntity; metadata: LoreMetadata; }
export interface ChatSource { id: string; label: string; chapterId?: string; sceneId?: string; entityId?: string; excerpt?: string; startOffset?: number; endOffset?: number; }
export interface TimelineEvent { id: string; title: string; storyTime: string; chapter: string; scene: string; location: string; characters: string[]; pov: string; summary: string; consequences: string; knowledge: string; clue?: string; status: EntityStatus; track: string; }
export interface MindNode { id: string; label: string; type: string; x: number; y: number; status?: EntityStatus; }
export interface MindEdge { id: string; source: string; target: string; label: string; }
export type TimelineEventStatus = 'proposed' | 'confirmed' | 'uncertain' | 'rejected';
export type TimelineTimeCertainty = 'exact' | 'relative' | 'unknown';
export interface PersistentTimelineEvent { id: string; projectId: string; bookId: string; chapterId: string; sceneId: string; passageUnitId?: string; title: string; summary: string; storyTimeText: string; normalizedTime?: string; temporalOrder: number; timeCertainty: TimelineTimeCertainty; locationEntityId?: string; povCharacterId?: string; participatingEntityIds: string[]; causeEventIds: string[]; consequenceEventIds: string[]; knowledgeChanges: string[]; stateChanges: string[]; relatedPlotThreadIds: string[]; sourceReferenceIds: string[]; confidence: number; status: TimelineEventStatus; authorConfirmed: boolean; origin: 'manuscript_analysis' | 'manual' | 'longform'; createdAt: string; updatedAt: string; }
export interface SavePersistentTimelineEventInput extends Omit<PersistentTimelineEvent, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface StoryGraphEdge { id: string; projectId: string; sourceEntityId: string; targetEntityId: string; relationType: string; label: string; validFromChapterId?: string; validFromSceneId?: string; validFromOffset?: number; validUntilChapterId?: string; validUntilSceneId?: string; validUntilOffset?: number; sourceReferenceIds: string[]; confidence: number; status: TimelineEventStatus; authorConfirmed: boolean; origin: 'manuscript_analysis' | 'manual' | 'longform'; createdAt: string; updatedAt: string; }
export interface SaveStoryGraphEdgeInput extends Omit<StoryGraphEdge, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface MindmapLayout { id: string; projectId: string; userId: string; nodeId: string; positionX: number; positionY: number; width: number; height: number; groupId?: string; hidden: boolean; fixed: boolean; updatedAt: string; }
export interface SaveMindmapLayoutInput extends Omit<MindmapLayout, 'id' | 'updatedAt'> { id?: string; }
export interface ChatMessage { id: string; role: 'user' | 'assistant'; content: string; sources?: ChatSource[]; time: string; }
export interface AiTask { id: string; type: AiTaskType; prompt: string; context: string[]; }
export interface ProviderStatus { available: boolean; label: string; detail: string; }
export type CodexAuthenticationState = 'authenticated' | 'notAuthenticated' | 'unknown';
export interface CodexCliCapabilities { installed: boolean; binaryPath?: string; version?: string; supportsExec: boolean; supportsJson: boolean; supportsEphemeral: boolean; supportsOutputSchema: boolean; supportsReadOnlySandbox: boolean; supportsSkipGitCheck: boolean; supportsModel: boolean; supportsDisableFeatures: boolean; authentication: CodexAuthenticationState; compatible: boolean; detail: string; }
export interface AiProviderSettings { activeProvider: 'local-prototype' | 'codex-cli'; codexBinaryPath?: string; codexModelOverride?: string; bibleUpdateTimeoutSeconds: number; chatTimeoutSeconds: number; allowLocalFallback: boolean; codexPrivacyAcknowledgedAt?: string; }
export type CodexTaskKind = 'extractBiblePatch' | 'extractCharacterMemoryPatch' | 'answerWithProjectContext' | 'analyzeProjectStyle' | 'summarizeScene' | 'summarizeChapter' | 'summarizeBook' | 'planChapterDraft' | 'draftChapterSection' | 'reviewChapterSection' | 'reviewCompleteChapter' | 'analyzeContinuityPassage' | 'analyzeLoreDraft' | 'buildLoreSheet' | 'detectBookGenre';
export interface GroundedChatResult { answer: string; usedEntityIds: string[]; usedSourceIds: string[]; uncertainty: 'low' | 'medium' | 'high'; warnings: string[]; }
export interface Correction { id: string; kind: CorrectionKind; from: string; to: string; reason: string; start: number; end: number; }
export interface CorrectionResult { id: string; sourceText: string; corrections: Correction[]; provider: string; message?: string; }

export type LoreCrafterRunStatus = 'pending' | 'running' | 'awaiting_review' | 'completed' | 'failed' | 'cancelled';
export type LoreCrafterItemStatus = 'proposed' | 'accepted' | 'rejected' | 'uncertain' | 'merged';
export type LoreCrafterClarificationStatus = 'open' | 'answered' | 'skipped';
export type LoreSheetDraftStatus = 'proposed' | 'reviewed' | 'rejected';
export type LoreCrafterExcludedTarget = 'character_memory' | 'plot_thread' | 'continuity_state' | 'manuscript' | 'style';
export interface LoreCrafterExcludedContent { content: string; suggestedTarget: LoreCrafterExcludedTarget; reason: string; }
export interface LoreCrafterAnalysis {
  understandingSummary: string;
  confirmedStatements: string[];
  proposedWorldRules: string[];
  prerequisites: string[];
  effects: string[];
  limitations: string[];
  costs: string[];
  exceptions: string[];
  terminology: string[];
  relevantOrganizations: string[];
  relevantLocations: string[];
  historicalBackground: string[];
  unresolvedQuestions: string[];
  contradictions: string[];
  excludedContent: LoreCrafterExcludedContent[];
  clarificationQuestions: string[];
  confidence: number;
  warnings: string[];
}
export interface BuildLoreSheetResult {
  title: string;
  premise: string;
  categories: string[];
  worldRules: string[];
  worldRuleObjects?: LoreSheetWorldRule[];
  prerequisites: string[];
  effects: string[];
  limitations: string[];
  costs: string[];
  exceptions: string[];
  terminology: string[];
  organizations: string[];
  locations: string[];
  historicalEvents: string[];
  knownAspects: string[];
  unknownAspects: string[];
  ruleConnections: string[];
  openQuestions: string[];
  warnings: string[];
}
export interface LoreSheetWorldRule { temporaryId: string; title: string; statement: string; prerequisites: string[]; effects: string[]; limitations: string[]; costs: string[]; exceptions: string[]; relatedTerminology: string[]; connectedItemIds: string[]; sourceSpans: Array<{ excerpt: string; startOffset: number; endOffset: number }>; confidence: number; }
export interface LoreCrafterRun { id: string; projectId: string; originalText: string; contentHash: string; providerId: string; promptVersion: string; status: LoreCrafterRunStatus; understandingSummary?: string; analysis?: LoreCrafterAnalysis; confirmationText?: string; createdAt: string; updatedAt: string; completedAt?: string; errorCode?: string; errorMessage?: string; }
export interface LoreCrafterClarification { id: string; runId: string; projectId: string; question: string; answer?: string; status: LoreCrafterClarificationStatus; createdAt: string; updatedAt: string; }
export interface LoreCrafterSourceReference { id: string; runId: string; projectId: string; excerpt: string; startOffset: number; endOffset: number; sourceDocumentId?: string; sourceReferenceId?: string; createdAt: string; }
export interface LoreSheetDraft { id: string; runId: string; projectId: string; contentHash: string; title: string; premise: string; categories: string[]; worldRules: string[]; prerequisites: string[]; effects: string[]; limitations: string[]; costs: string[]; exceptions: string[]; terminology: string[]; organizations: string[]; locations: string[]; historicalEvents: string[]; knownAspects: string[]; unknownAspects: string[]; ruleConnections: string[]; openQuestions: string[]; status: LoreSheetDraftStatus; createdAt: string; updatedAt: string; }
export interface LoreSheetItem { id: string; draftId: string; runId: string; projectId: string; itemType: string; title: string; content: string; confidence: number; structured?: Record<string, unknown>; sourceReferenceId?: string; targetEntityId?: string; targetRuleId?: string; status: LoreCrafterItemStatus; createdAt: string; updatedAt: string; }
export interface CreateLoreCrafterRunInput { projectId: string; originalText: string; contentHash: string; providerId: string; promptVersion: string; }
export interface UpdateLoreCrafterRunInput { id: string; status: LoreCrafterRunStatus; understandingSummary?: string; analysis?: LoreCrafterAnalysis; confirmationText?: string; errorCode?: string; errorMessage?: string; completedAt?: string; }
export interface SaveLoreCrafterClarificationInput { id?: string; runId: string; projectId: string; question: string; answer?: string; status?: LoreCrafterClarificationStatus; }
export interface SaveLoreCrafterSourceInput { runId: string; projectId: string; excerpt: string; startOffset: number; endOffset: number; }
export interface SaveLoreSheetDraftInput extends Omit<LoreSheetDraft, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface SaveLoreSheetItemInput extends Omit<LoreSheetItem, 'id' | 'createdAt' | 'updatedAt' | 'status'> { id?: string; status?: LoreCrafterItemStatus; }
export type ManuscriptAnalysisArtifactReviewStatus = 'pending' | 'confirmed' | 'rejected' | 'uncertain' | 'skipped';
export type ManuscriptAnalysisArtifactType = 'bible_proposal' | 'character_memory_proposal' | 'continuity_finding' | 'import_draft_state' | 'project_rule_proposal' | 'plot_thread_proposal' | 'narrative_summary' | 'book_end_state_proposal' | 'global_countercheck_finding' | 'timeline_event' | 'story_graph_edge' | 'provisional_entity' | 'provisional_merge' | 'genre_detection';
export interface ManuscriptAnalysisPhaseResult { id: string; jobId: string; projectId: string; phase: ManuscriptAnalysisPhase; resultKind: string; payload: Record<string, unknown>; contentHash: string; providerId: string; promptVersion: string; reviewStatus: ManuscriptAnalysisArtifactReviewStatus; createdAt: string; updatedAt: string; }
export interface SaveManuscriptAnalysisPhaseResultInput extends Omit<ManuscriptAnalysisPhaseResult, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface ManuscriptAnalysisArtifact { id: string; jobId: string; projectId: string; phase: ManuscriptAnalysisPhase; unitId?: string; artifactType: ManuscriptAnalysisArtifactType; artifactId: string; reviewStatus: ManuscriptAnalysisArtifactReviewStatus; explicitlySkipped: boolean; createdAt: string; updatedAt: string; }
export interface SaveManuscriptAnalysisArtifactInput extends Omit<ManuscriptAnalysisArtifact, 'id' | 'createdAt' | 'updatedAt'> { id?: string; }
export interface ManuscriptAnalysisReviewAudit { id: string; jobId: string; projectId: string; action: 'skip_open_artifacts' | 'complete_review'; artifactIds: string[]; artifactTypes: ManuscriptAnalysisArtifactType[]; note: string; createdAt: string; }
export interface ManuscriptAnalysisCompletionReport { id: string; jobId: string; projectId: string; contentHash: string; payload: { recognizedScenes: unknown[]; entities: unknown[]; merges: unknown[]; bibleDecisions: unknown[]; memoryDecisions: unknown[]; continuityFindings: unknown[]; timelineEvents: unknown[]; graphEdges: unknown[]; plotThreads: unknown[]; skippedResults: unknown[]; uncertainResults: unknown[]; rejectedResults: unknown[]; providers: string[]; promptVersions: string[]; warnings: string[]; truncations: string[]; }; createdAt: string; updatedAt: string; }
export interface SaveManuscriptAnalysisCompletionReportInput { id?: string; jobId: string; projectId: string; contentHash: string; payload: ManuscriptAnalysisCompletionReport['payload']; }
export interface SaveManuscriptAnalysisReviewAuditInput extends Omit<ManuscriptAnalysisReviewAudit, 'id' | 'createdAt'> { id?: string; }

export interface WorkspaceSnapshot { project: Project; books: Book[]; chapters: Chapter[]; entities: StoryEntity[]; }
export interface CreateProjectInput { title: string; author: string; description?: string; volumeTitle?: string; volume?: number; }
export interface CreateChapterInput { bookId: string; title: string; }
export interface UpdateChapterInput { id: string; title: string; }
export interface CreateSceneInput { chapterId: string; title: string; }
export type UpdateSceneInput = Scene;
export interface CreateSceneVersionInput { sceneId: string; reason?: SceneVersionReason; }
export interface ManuscriptImportChapterInput { title: string; content: string; }
export interface CreateManuscriptImportPageMarkerInput { pageNumber: number; label: string; sourceOffset: number; textOffset: number; }
export interface CreateManuscriptImportUnitInput { pageNumber?: number; startOffset: number; endOffset: number; content: string; contentHash: string; }
export interface CreateManuscriptImportChapterInput extends ManuscriptImportChapterInput { pageMarkers: CreateManuscriptImportPageMarkerInput[]; units: CreateManuscriptImportUnitInput[]; }
export interface CreateManuscriptImportInput { projectId: string; bookId: string; originalText: string; originalContentHash: string; fileName: string; sourceKind?: 'external_text'; chapters: CreateManuscriptImportChapterInput[]; providerId: string; newVersion?: boolean; onboarding?: SaveProjectOnboardingStateInput; }
export interface ManuscriptImportVersion { id: string; projectId: string; bookId: string; sourceDocumentId: string; originalContentHash: string; versionNumber: number; status: 'active' | 'archived' | 'cancelled'; analysisJobId?: string; createdAt: string; activatedAt?: string; }
export interface ManuscriptImportWorkflowResult { importVersion: ManuscriptImportVersion; sourceDocument: ProjectSourceDocument; import: ManuscriptImportResult; analysisJob: ManuscriptAnalysisJob; }
export type ManuscriptFormat = 'txt' | 'markdown' | 'docx';
export interface ManuscriptImportInput { projectId: string; bookId: string; chapters: ManuscriptImportChapterInput[]; }
export interface ManuscriptImportResult { chapters: Chapter[]; scenes: Scene[]; versions: SceneVersion[]; }
export interface SaveStoryEntityInput extends StoryEntity { projectId: string; }
export interface CreateStoryEntityInput { projectId: string; name: string; type: EntityType; description: string; status: EntityStatus; confidence: number; chapterId?: string; sceneId?: string; excerpt: string; authorConfirmed: boolean; tags: string[]; origin?: StoryEntityOrigin; }
export interface UpdateStoryEntityInput extends CreateStoryEntityInput { id: string; }
export interface CreateSourceReferenceInput { projectId: string; entityId?: string; proposalId?: string; chapterId: string; sceneId: string; excerpt: string; startOffset?: number; endOffset?: number; }
export interface CreateBibleUpdateRunInput { projectId: string; sceneId: string; sceneUpdatedAt: string; contentHash: string; extractorId: string; analyzedContent?: string; force?: boolean; }
export type BibleReviewDecision = 'accept' | 'edit_accept' | 'save_uncertain' | 'save_author_note' | 'reject' | 'keep_existing' | 'mark_contradiction' | 'accept_new_value' | 'accept_retcon' | 'defer';
export interface ReviewBibleProposalInput { proposalId: string; reviewStatus: BibleReviewStatus; decision?: BibleReviewDecision; candidateName?: string; candidateDescription?: string; candidateStatus?: EntityStatus; classification?: BibleClassification; }
export interface PendingSourceNavigation { sceneId: string; chapterId: string; excerpt: string; startOffset?: number; endOffset?: number; }

export type EndingStatus = 'fixed' | 'preferred' | 'open';
export interface RevealConstraint { entityId: string; notBeforeChapter?: number; instruction: string; }
export interface StoryDirection { projectId: string; premise: string; currentStoryPhase: string; bookGoal: string; plannedEnding: string; endingStatus: EndingStatus; centralTwist: string; thematicGoal: string; mustHappen: string[]; mustNotHappen: string[]; nextTurningPoint: string; revealConstraints: RevealConstraint[]; authorNotes: string; createdAt: string; updatedAt: string; }
export type SaveStoryDirectionInput = Omit<StoryDirection, 'createdAt' | 'updatedAt'>;
export interface WritingPreferences { projectId: string; wordsPerPage: number; preferredSectionWords: number; maximumSectionWords: number; defaultSceneCount: number; requirePlanConfirmation: boolean; requireFinalConfirmation: boolean; createdAt: string; updatedAt: string; }
export type SaveWritingPreferencesInput = Omit<WritingPreferences, 'createdAt' | 'updatedAt'>;
export type ChapterGenerationStatus = 'preparing' | 'needs_input' | 'planning' | 'plan_ready' | 'generating' | 'reviewing' | 'draft_ready' | 'accepted' | 'cancelled' | 'failed';
export interface ChapterGenerationJob { id: string; projectId: string; targetBookId: string; targetAfterChapterId?: string; requestedPages?: number; targetWords: number; requestedSceneCount?: number; userInstruction: string; status: ChapterGenerationStatus; activeProvider: string; contentContextHash: string; contextOverrideAccepted?: boolean; lastResumedAt?: string; createdAt: string; updatedAt: string; completedAt?: string; errorMessage?: string; }
export interface CreateChapterGenerationJobInput { projectId: string; targetBookId: string; targetAfterChapterId?: string; requestedPages?: number; targetWords: number; requestedSceneCount?: number; userInstruction: string; activeProvider: string; contentContextHash: string; }
export interface AcceptChapterGenerationJobInput { jobId: string; currentContextHash: string; }
export interface PlannedKnowledgeChange { characterId: string; factEntityId: string; nextState: CharacterKnowledgeKind; reason: string; }
export interface PlannedRelationshipChange { characterAId: string; characterBId: string; change: string; reason: string; }
export interface ChapterPlanBeat { id: string; orderIndex: number; title: string; purpose: string; location?: string; povCharacterId?: string; participatingCharacterIds: string[]; startingState: string; event: string; conflict: string; newInformation: string[]; knowledgeChanges: PlannedKnowledgeChange[]; relationshipChanges: PlannedRelationshipChange[]; cluesUsed: string[]; loreEntityIds: string[]; endingHook: string; targetWords: number; }
export interface ChapterGenerationPlan { id: string; jobId: string; chapterTitle: string; chapterGoal: string; povCharacterId?: string; startingState: string; endingState: string; chapterSummary: string; endingConnection: string; newInformation: string[]; withheldInformation: string[]; beats: ChapterPlanBeat[]; reviewStatus: 'pending' | 'accepted' | 'edited' | 'rejected'; reviewedAt?: string; createdAt: string; updatedAt: string; }
export type SaveChapterGenerationPlanInput = Omit<ChapterGenerationPlan, 'id' | 'createdAt' | 'updatedAt' | 'reviewedAt'> & { reviewStatus: ChapterGenerationPlan['reviewStatus']; };
export interface DraftCharacterState { characterId: string; state: string; change: string; }
export interface DraftObjectState { objectId: string; location: string; state: string; }
export interface DraftInjuryState { characterId: string; description: string; severity: string; }
export interface DraftContinuityState { currentLocation: string; currentStoryTime: string; presentCharacterIds: string[]; characterStates: DraftCharacterState[]; establishedFacts: string[]; knowledgeChanges: PlannedKnowledgeChange[]; relationshipChanges: PlannedRelationshipChange[]; movedObjects: DraftObjectState[]; injuries: DraftInjuryState[]; cluesIntroduced: string[]; promisesCreated: string[]; unresolvedActions: string[]; lastParagraphSummary: string; }
export type ChapterGenerationDraftState = 'valid' | 'stale' | 'regenerate_requested';
export interface ChapterGenerationSection { id: string; jobId: string; planBeatId: string; orderIndex: number; targetWords: number; actualWords: number; content: string; contentHash?: string; draftContextHash?: string; draftState?: ChapterGenerationDraftState; continuationSummary: string; continuityState: DraftContinuityState; status: 'pending' | 'generating' | 'generated' | 'reviewed' | 'regenerate_requested' | 'failed'; providerId?: string; createdAt: string; updatedAt: string; }
export type SaveChapterGenerationSectionInput = Omit<ChapterGenerationSection, 'id' | 'actualWords' | 'createdAt' | 'updatedAt'>;
export interface ChapterGenerationReview { id: string; jobId: string; sectionId?: string; continuityRunId?: string; reviewScope: 'section' | 'chapter'; issueType: string; severity: 'info' | 'warning' | 'blocking'; title: string; description: string; relatedEntityIds: string[]; relatedSourceIds: string[]; suggestedAction: string; status: string; createdAt: string; updatedAt: string; }
export type SaveChapterGenerationReviewInput = Omit<ChapterGenerationReview, 'id' | 'createdAt' | 'updatedAt' | 'jobId'> & { jobId?: string };
export type ChapterGenerationDraftLedgerStatus = 'proposed' | 'superseded' | 'rejected' | 'accepted_for_manuscript_review';
export interface ChapterGenerationDraftLedgerEntry { id: string; jobId: string; sectionId: string; projectId: string; entityId: string; relatedEntityId?: string; stateKind: ContinuityStateKind; previousState: string; newState: string; sourceExcerpt: string; sourceStartOffset?: number; sourceEndOffset?: number; contentHash: string; confidence: number; status: ChapterGenerationDraftLedgerStatus; sourceReferenceId?: string; createdAt: string; updatedAt: string; }
export interface SaveChapterGenerationDraftLedgerInput extends Omit<ChapterGenerationDraftLedgerEntry, 'id' | 'createdAt' | 'updatedAt' | 'status'> { id?: string; status?: ChapterGenerationDraftLedgerStatus; }
export interface ChapterDraftPlanResult extends Omit<ChapterGenerationPlan, 'id' | 'jobId' | 'reviewStatus' | 'createdAt' | 'updatedAt'> { assumptions: { type: string; text: string }[]; warnings: string[]; }
export interface ChapterSectionDraftResult { content: string; continuationSummary: string; continuityState: DraftContinuityState; usedEntityIds: string[]; usedMemoryIds: string[]; usedSourceIds: string[]; warnings: string[]; }
