import { useEffect, useState } from 'react';
import { Archive, Eye, EyeOff } from 'lucide-react';
import type { RevealAudienceState, RevealClueRule, RevealContract } from '../../types/domain';
import type { StoryRepository } from '../../services/storyRepository';

interface Props { projectId: string; repository: StoryRepository; }
const stateLabels: Record<RevealContract['revealState'], string> = { author_only: 'Nur für dich', foreshadowed: 'Wird angedeutet', reader_revealed: 'Leser kennt es' };
export function RevealContractsView({ projectId, repository }: Props) {
  const [contracts, setContracts] = useState<RevealContract[]>([]); const [selected, setSelected] = useState<RevealContract>(); const [audience, setAudience] = useState<RevealAudienceState[]>([]); const [clues, setClues] = useState<RevealClueRule[]>([]); const [showTruth, setShowTruth] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void repository.listRevealContracts(projectId).then(setContracts).catch((cause) => setError(cause instanceof Error ? cause.message : 'Enthüllungen konnten nicht geladen werden.')); }, [projectId, repository]);
  useEffect(() => { if (!selected) { setAudience([]); setClues([]); return; } void Promise.all([repository.listRevealAudienceStates(projectId, selected.id), repository.listRevealClueRules(projectId, selected.id)]).then(([states, rules]) => { setAudience(states); setClues(rules); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Enthüllungsregeln konnten nicht geladen werden.')); }, [projectId, repository, selected]);
  const archive = async () => { if (!selected) return; try { const archived = await repository.retireRevealContract(projectId, selected.id); setContracts((items) => items.map((item) => item.id === archived.id ? archived : item)); setSelected(archived); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enthüllung konnte nicht archiviert werden.'); } };
  return <section className="reveal-contracts-view"><div className="view-heading"><div><span className="eyebrow">STORY BIBLE · GEHEIMNISSE & ENTHÜLLUNGEN</span><h2>Geheimnisse & Enthüllungen</h2><p>Hier legst du fest, was wahr ist, wer was wissen darf und welche Hinweise vorher möglich sind.</p></div></div>{error && <div className="save-error" role="alert">{error}</div>}<div className="bible-layout"><div className="entity-list"><div className="list-summary"><span>{contracts.length} Wahrheiten</span></div>{contracts.map((contract) => <button className={`entity-row ${contract.id === selected?.id ? 'active' : ''}`} key={contract.id} onClick={() => { setSelected(contract); setShowTruth(false); }}><span className="entity-icon secret">?</span><span className="entity-row-main"><strong>{contract.title}</strong><span>{stateLabels[contract.revealState]}</span></span><span className={`status-pill ${contract.status === 'confirmed' ? 'green' : 'purple'}`}>{contract.status === 'confirmed' ? 'Aktiv' : 'Entwurf'}</span></button>)}{!contracts.length && <p className="empty-state">Noch keine Geheimnisse eingerichtet. Starte sie aus einer Lore-Analyse.</p>}</div>{selected ? <div className="entity-detail reveal-contract-detail"><div className="detail-top"><div><span className="status-pill purple">{stateLabels[selected.revealState]}</span><h2>{selected.title}</h2></div><button className="icon-button" onClick={() => void archive()} title="Enthüllung archivieren"><Archive size={16} /></button></div><div className="reveal-truth-box"><button className="ghost-button" onClick={() => setShowTruth((value) => !value)}>{showTruth ? <EyeOff size={14} /> : <Eye size={14} />} {showTruth ? 'Wahrheit verbergen' : 'Geheime Wahrheit anzeigen'}</button>{showTruth && <p>{selected.truthStatement}</p>}</div><h3>Leser- und Figurenpfade</h3><p>{audience.length} Wissensstände gespeichert.</p><h3>Hinweise</h3><p>{clues.filter((rule) => rule.ruleKind === 'allowed').length} erlaubt · {clues.filter((rule) => rule.ruleKind === 'forbidden').length} zu eindeutig · {clues.filter((rule) => rule.ruleKind === 'required').length} erforderlich</p>{selected.revealConditionText && <><h3>Voraussetzung für die Enthüllung</h3><p>{selected.revealConditionText}</p></>}</div> : <div className="empty-state">Wähle eine Wahrheit aus.</div>}</div></section>;
}
