import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Plus, X } from 'lucide-react';
import type { Chapter, RevealCandidate, RevealCandidateClue, RevealCandidateSubjectType, RevealKnowledgeLevel, RevealPosition, StoryEntity } from '../../types/domain';
import type { StoryRepository } from '../../services/storyRepository';

interface Props { projectId: string; candidate: RevealCandidate; entities: StoryEntity[]; chapters: Chapter[]; repository: StoryRepository; onClose: () => void; onSaved?: () => void; }
type ClueKind = 'allowed' | 'forbidden' | 'required';
const levelLabels: Record<RevealKnowledgeLevel, string> = { unknown: 'Weiß nichts', suspects: 'Vermutet etwas', partial: 'Kennt einen Teil', knows: 'Kennt die Wahrheit', false_belief: 'Glaubt etwas Falsches' };
const typeLabels: Record<RevealCandidateSubjectType, string> = { secret: 'Geheimnis', fact: 'Fakt', world_rule: 'Weltregel' };
const clueLabels: Record<ClueKind, string> = { allowed: 'Darf vorkommen', forbidden: 'Darf vor der Enthüllung nicht vorkommen', required: 'Muss vorher vorbereitet werden' };
const position = (chapter?: Chapter, sceneId?: string): RevealPosition => ({ chapterId: chapter?.id, sceneId, chapterOrderIndex: chapter?.orderIndex, sceneOrderIndex: chapter?.scenes.find((scene) => scene.id === sceneId)?.orderIndex });

export function RevealWizard({ projectId, candidate, entities, chapters, repository, onClose, onSaved }: Props) {
  const [step, setStep] = useState(1); const [title, setTitle] = useState(candidate.title); const [truth, setTruth] = useState(candidate.truthStatement); const [subjectType, setSubjectType] = useState(candidate.suggestedSubjectType); const [authorConfirmed, setAuthorConfirmed] = useState(false); const [revealState, setRevealState] = useState(candidate.suggestedRevealState); const [condition, setCondition] = useState(candidate.suggestedRevealCondition); const [readerLevel, setReaderLevel] = useState(candidate.suggestedReaderStartLevel); const [readerChapterId, setReaderChapterId] = useState(''); const [readerSceneId, setReaderSceneId] = useState(''); const [characters, setCharacters] = useState<Array<{ entityId: string; level: RevealKnowledgeLevel; belief: string; chapterId: string; sceneId: string }>>([]); const [clues, setClues] = useState<Array<{ kind: ClueKind; description: string; explicitness: RevealCandidateClue['maximumExplicitness'] }>>([...candidate.suggestedAllowedClues.map((item) => ({ kind: 'allowed' as const, description: item.description, explicitness: item.maximumExplicitness })), ...candidate.suggestedForbiddenClues.map((item) => ({ kind: 'forbidden' as const, description: item.description, explicitness: item.maximumExplicitness })), ...candidate.suggestedRequiredClues.map((item) => ({ kind: 'required' as const, description: item.description, explicitness: item.maximumExplicitness }))]); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const revealChapter = chapters.find((chapter) => chapter.id === readerChapterId); const revealScene = revealChapter?.scenes.find((scene) => scene.id === readerSceneId);
  const charactersByName = useMemo(() => entities.filter((entity) => entity.type === 'character'), [entities]);
  const addCharacter = () => setCharacters((items) => [...items, { entityId: '', level: 'unknown', belief: '', chapterId: '', sceneId: '' }]);
  const addClue = (kind: ClueKind) => setClues((items) => [...items, { kind, description: '', explicitness: 'subtle' }]);
  const currentPosition = () => position(revealChapter, readerSceneId || undefined);
  const save = async (activate: boolean) => {
    if (!title.trim() || !truth.trim()) { setError('Titel und objektive Wahrheit sind erforderlich.'); return; }
    if (activate && !authorConfirmed) { setError('Bestätige zuerst ausdrücklich, dass diese Aussage objektiv wahr ist.'); return; }
    setBusy(activate ? 'activate' : 'draft'); setError('');
    try {
      const subjectId = candidate.temporaryId;
      const readerStates = readerChapterId ? [
        { projectId, contractId: subjectId, audienceKind: 'reader' as const, knowledgeLevel: readerLevel, beliefText: '', validFromPosition: {}, validUntilPosition: currentPosition(), status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate },
        { projectId, contractId: subjectId, audienceKind: 'reader' as const, knowledgeLevel: 'knows' as const, beliefText: 'Die Wahrheit ist ab diesem Punkt vollständig enthüllt.', validFromPosition: currentPosition(), validUntilPosition: undefined, status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate },
      ] : [{ projectId, contractId: subjectId, audienceKind: 'reader' as const, knowledgeLevel: readerLevel, beliefText: '', validFromPosition: {}, validUntilPosition: undefined, status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate }];
      const audienceStates = [
        ...readerStates,
        ...characters.filter((item) => item.entityId).map((item) => ({ projectId, contractId: subjectId, audienceKind: 'character' as const, characterEntityId: item.entityId, knowledgeLevel: item.level, beliefText: item.belief, validFromPosition: position(chapters.find((chapter) => chapter.id === item.chapterId), item.sceneId || undefined), status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate })),
      ];
      const clueRules = clues.filter((item) => item.description.trim()).map((item) => ({ projectId, contractId: subjectId, ruleKind: item.kind, clueType: 'foreshadowing', description: item.description, maximumExplicitness: item.explicitness, validFromPosition: undefined, validUntilPosition: undefined, status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate }));
      const contract = { projectId, subjectEntityId: subjectId, title, truthStatement: truth, scope: 'book' as const, status: activate ? 'confirmed' as const : 'proposed' as const, authorConfirmed: activate, revealState, plannedRevealBookId: revealChapter ? chapters.find((chapter) => chapter.id === revealChapter.id)?.bookId : undefined, plannedRevealChapterId: revealChapter?.id, plannedRevealSceneId: revealScene?.id, plannedRevealOffset: undefined, revealConditionText: condition, notes: 'Aus dem geführten Reveal-Wizard.' };
      if (activate) await repository.activateRevealContractBundle({ projectId, subjectEntity: { id: subjectId, name: title, type: subjectType, description: truth, tags: ['reveal'] }, contract, audienceStates, clueRules });
      else { const entity = await repository.createStoryEntity({ projectId, name: title, type: subjectType, description: truth, status: 'proposed', confidence: candidate.confidence, excerpt: candidate.sourceExcerpt, authorConfirmed: false, tags: ['reveal'] }); const savedContract = await repository.saveRevealContract({ ...contract, subjectEntityId: entity.id }); for (const state of audienceStates) await repository.saveRevealAudienceState({ ...state, contractId: savedContract.id }); for (const rule of clueRules) await repository.saveRevealClueRule({ ...rule, contractId: savedContract.id }); }
      onSaved?.(); onClose();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Der Reveal-Entwurf konnte nicht gespeichert werden.'); } finally { setBusy(''); }
  };
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal reveal-wizard"><div className="modal-head"><div><span className="eyebrow">GEHEIMNIS & ENTHÜLLUNG · SCHRITT {step} VON 6</span><h2>{['', 'Was ist wirklich wahr?', 'Was weiß der Leser?', 'Wer weiß was?', 'Welche Hinweise sind erlaubt?', 'Wann wird die Wahrheit enthüllt?', 'Zusammenfassung'][step]}</h2></div><button className="icon-button" onClick={onClose} aria-label="Wizard schließen"><X size={18} /></button></div><div className="wizard-progress">{[1, 2, 3, 4, 5, 6].map((number) => <span key={number} className={number <= step ? 'active' : ''}>{number}</span>)}</div>{error && <div className="save-error" role="alert">{error}</div>}
    {step === 1 && <div className="wizard-step"><p>StoryMemory darf diese Wahrheit intern kennen. Das bedeutet nicht, dass sie bereits im Manuskript oder für den Leser sichtbar ist.</p><label className="field-label">Titel<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="field-label">Objektive Wahrheit<textarea rows={4} value={truth} onChange={(event) => setTruth(event.target.value)} /></label><label className="field-label">Einordnung<select value={subjectType} onChange={(event) => setSubjectType(event.target.value as RevealCandidateSubjectType)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="checkline"><input type="checkbox" checked={authorConfirmed} onChange={(event) => setAuthorConfirmed(event.target.checked)} /> Ja, diese Aussage ist objektiv wahr</label></div>}
    {step === 2 && <div className="wizard-step"><p>Lege fest, wie sich das Wissen des Lesers entwickelt. „Noch nicht festgelegt“ ist jederzeit möglich.</p><label className="field-label">Am Projektanfang<select value={readerLevel} onChange={(event) => setReaderLevel(event.target.value as RevealKnowledgeLevel)}>{Object.entries(levelLabels).filter(([value]) => value !== 'false_belief').map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="form-grid"><label className="field-label">Ab Kapitel<select value={readerChapterId} onChange={(event) => { setReaderChapterId(event.target.value); setReaderSceneId(''); }}><option value="">Noch nicht festgelegt</option>{chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><label className="field-label">Ab Szene<select value={readerSceneId} onChange={(event) => setReaderSceneId(event.target.value)} disabled={!revealChapter}><option value="">Kapitelanfang</option>{revealChapter?.scenes.map((scene) => <option key={scene.id} value={scene.id}>{scene.title}</option>)}</select></label></div></div>}
    {step === 3 && <div className="wizard-step"><p>Figurenwissen gilt nur für die ausgewählte Figur. Namen werden nicht automatisch zusammengeführt.</p>{characters.map((item, index) => <div className="wizard-row" key={`${index}-${item.entityId}`}><select aria-label="Figur auswählen" value={item.entityId} onChange={(event) => setCharacters((items) => items.map((entry, itemIndex) => itemIndex === index ? { ...entry, entityId: event.target.value } : entry))}><option value="">Figur auswählen</option>{charactersByName.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select><select aria-label="Wissensstand" value={item.level} onChange={(event) => setCharacters((items) => items.map((entry, itemIndex) => itemIndex === index ? { ...entry, level: event.target.value as RevealKnowledgeLevel } : entry))}>{Object.entries(levelLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{item.level === 'false_belief' && <input aria-label="Falsche Überzeugung" placeholder="Was glaubt die Figur stattdessen?" value={item.belief} onChange={(event) => setCharacters((items) => items.map((entry, itemIndex) => itemIndex === index ? { ...entry, belief: event.target.value } : entry))} />}<button className="icon-button" onClick={() => setCharacters((items) => items.filter((_, itemIndex) => itemIndex !== index))} aria-label="Figurenwissen entfernen"><X size={14} /></button></div>)}<button className="ghost-button" onClick={addCharacter}><Plus size={14} /> Figur hinzufügen</button></div>}
    {step === 4 && <div className="wizard-step">{(['allowed', 'forbidden', 'required'] as ClueKind[]).map((kind) => <section className="wizard-clue-group" key={kind}><h3>{clueLabels[kind]}</h3>{clues.map((item, index) => item.kind === kind && <div className="wizard-row" key={index}><input aria-label="Hinweis" value={item.description} placeholder="Beschreibe den Hinweis" onChange={(event) => setClues((items) => items.map((entry, itemIndex) => itemIndex === index ? { ...entry, description: event.target.value } : entry))} /><select aria-label="Hinweisstärke" value={item.explicitness} onChange={(event) => setClues((items) => items.map((entry, itemIndex) => itemIndex === index ? { ...entry, explicitness: event.target.value as RevealCandidateClue['maximumExplicitness'] } : entry))}><option value="subtle">Sehr subtil</option><option value="suggestive">Auffällig</option><option value="strong">Stark</option><option value="direct">Direkt</option></select><button className="icon-button" onClick={() => setClues((items) => items.filter((_, itemIndex) => itemIndex !== index))} aria-label="Hinweis entfernen"><X size={14} /></button></div>)}<button className="text-button" onClick={() => addClue(kind)}><Plus size={13} /> Hinweis hinzufügen</button></section>)}</div>}
    {step === 5 && <div className="wizard-step"><p>Eine Enthüllung kann zunächst nur über eine Bedingung festgelegt werden. Eine Position bleibt optional.</p><label className="field-label">Enthüllungsbedingung<textarea rows={4} value={condition} onChange={(event) => setCondition(event.target.value)} placeholder="Was muss geschehen, damit die Enthüllung stattfinden darf?" /></label><label className="field-label">Geplanter Status<select value={revealState} onChange={(event) => setRevealState(event.target.value as typeof revealState)}><option value="author_only">Nur für dich</option><option value="foreshadowed">Wird angedeutet</option><option value="reader_revealed">Leser kennt es</option></select></label></div>}
    {step === 6 && <div className="wizard-step"><div className="reveal-summary"><strong>{title}</strong><p>{truth}</p><span>{authorConfirmed ? 'Objektiv bestätigt' : 'Noch unsicher'} · {revealState === 'author_only' ? 'Nur für dich' : revealState === 'foreshadowed' ? 'Wird angedeutet' : 'Leser kennt es'}</span><h4>Leser</h4><p>{levelLabels[readerLevel]}{revealChapter ? ` ab ${revealChapter.title}` : ' ab Projektanfang'}</p><h4>Hinweise</h4><p>{clues.filter((item) => item.description.trim()).length} Regeln vorbereitet · {characters.filter((item) => item.entityId).length} Figurenpfade</p></div><p>Erst mit der ausdrücklichen Aktivierung verwendet StoryMemory diese Angaben als verbindliche Schreib- und Prüfregeln.</p></div>}
    {busy && <p className="save-hint">Wird gespeichert …</p>}<div className="modal-actions"><button className="ghost-button" onClick={() => step === 1 ? onClose() : setStep((value) => value - 1)} disabled={Boolean(busy)}><ArrowLeft size={14} /> Zurück</button>{step < 6 ? <button className="primary-button" onClick={() => setStep((value) => value + 1)} disabled={Boolean(busy)}><ArrowRight size={14} /> Weiter</button> : <><button className="ghost-button" onClick={() => void save(false)} disabled={Boolean(busy)}>Als unbestätigten Entwurf speichern</button><button className="primary-button" onClick={() => void save(true)} disabled={Boolean(busy) || !authorConfirmed}><Check size={14} /> Geheimnis und Wissensregeln aktivieren</button></>}</div></div></div>;
}
