import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Plus, X } from 'lucide-react';
import type { Book, Chapter, RevealAudienceState, RevealCandidate, RevealCandidateClue, RevealCandidateSubjectType, RevealClueRule, RevealContract, RevealKnowledgeLevel, RevealPosition, StoryEntity } from '../../types/domain';
import type { StoryRepository } from '../../services/storyRepository';

interface Props {
  projectId: string;
  candidate: RevealCandidate;
  entities: StoryEntity[];
  chapters: Chapter[];
  books?: Book[];
  repository: StoryRepository;
  onClose: () => void;
  onSaved?: (result: { mode: 'draft' | 'activate'; artifactId: string }) => void | Promise<void>;
  existingContract?: RevealContract;
  existingAudienceStates?: RevealAudienceState[];
  existingClueRules?: RevealClueRule[];
}
type ClueKind = 'allowed' | 'forbidden' | 'required';
type TimelineEntry = { id: string; level: RevealKnowledgeLevel; belief: string; chapterId: string; sceneId: string; untilChapterId: string; untilSceneId: string; description: string };
type CharacterPath = { id: string; entityId: string; entries: TimelineEntry[] };
const levelLabels: Record<RevealKnowledgeLevel, string> = { unknown: 'Weiß nichts', suspects: 'Vermutet etwas', partial: 'Kennt einen Teil', knows: 'Kennt die Wahrheit', false_belief: 'Glaubt etwas Falsches' };
const typeLabels: Record<RevealCandidateSubjectType, string> = { secret: 'Geheimnis', fact: 'Fakt', world_rule: 'Weltregel' };
const clueLabels: Record<ClueKind, string> = { allowed: 'Darf vorkommen', forbidden: 'Darf vor der Enthüllung nicht vorkommen', required: 'Muss vorher vorbereitet werden' };
const newId = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const position = (chapters: Chapter[], chapterId: string, sceneId: string, offset?: number): RevealPosition => { const chapter = chapters.find((item) => item.id === chapterId); const scene = chapter?.scenes.find((item) => item.id === sceneId); return { bookId: chapter?.bookId, chapterId: chapter?.id, sceneId: scene?.id, chapterOrderIndex: chapter?.orderIndex, sceneOrderIndex: scene?.orderIndex, offset }; };
const emptyEntry = (level: RevealKnowledgeLevel = 'unknown'): TimelineEntry => ({ id: newId(), level, belief: '', chapterId: '', sceneId: '', untilChapterId: '', untilSceneId: '', description: '' });

function entryFromState(state: RevealAudienceState): TimelineEntry { return { id: state.id, level: state.knowledgeLevel, belief: state.beliefText, chapterId: state.validFromPosition.chapterId ?? '', sceneId: state.validFromPosition.sceneId ?? '', untilChapterId: state.validUntilPosition?.chapterId ?? '', untilSceneId: state.validUntilPosition?.sceneId ?? '', description: state.beliefText }; }

export function RevealWizard({ projectId, candidate, entities, chapters, books = [], repository, onClose, onSaved, existingContract, existingAudienceStates = [], existingClueRules = [] }: Props) {
  const initialReader = existingAudienceStates.filter((item) => item.audienceKind === 'reader').map(entryFromState);
  const initialCharacters = entities.filter((entity) => entity.type === 'character').map((entity) => ({ entity, entries: existingAudienceStates.filter((item) => item.audienceKind === 'character' && item.characterEntityId === entity.id).map(entryFromState) })).filter((item) => item.entries.length);
  const [step, setStep] = useState(1);
  const [title, setTitle] = useState(existingContract?.title ?? candidate.title);
  const [truth, setTruth] = useState(existingContract?.truthStatement ?? candidate.truthStatement);
  const [subjectType, setSubjectType] = useState<RevealCandidateSubjectType>(candidate.suggestedSubjectType);
  const [authorConfirmed, setAuthorConfirmed] = useState(existingContract?.authorConfirmed ?? false);
  const [revealState, setRevealState] = useState(existingContract?.revealState ?? candidate.suggestedRevealState);
  const [condition, setCondition] = useState(existingContract?.revealConditionText ?? candidate.suggestedRevealCondition);
  const [readerTimeline, setReaderTimeline] = useState<TimelineEntry[]>(initialReader.length ? initialReader : [emptyEntry(candidate.suggestedReaderStartLevel)]);
  const [characters, setCharacters] = useState<CharacterPath[]>(initialCharacters.map((item) => ({ id: newId(), entityId: item.entity.id, entries: item.entries })));
  const [revealBookId, setRevealBookId] = useState(existingContract?.plannedRevealBookId ?? '');
  const [revealChapterId, setRevealChapterId] = useState(existingContract?.plannedRevealChapterId ?? '');
  const [revealSceneId, setRevealSceneId] = useState(existingContract?.plannedRevealSceneId ?? '');
  const [revealOffset, setRevealOffset] = useState(existingContract?.plannedRevealOffset?.toString() ?? '');
  const [clues, setClues] = useState<Array<{ id: string; kind: ClueKind; description: string; explicitness: RevealCandidateClue['maximumExplicitness'] }>>([...candidate.suggestedAllowedClues.map((item) => ({ id: newId(), kind: 'allowed' as const, description: item.description, explicitness: item.maximumExplicitness })), ...candidate.suggestedForbiddenClues.map((item) => ({ id: newId(), kind: 'forbidden' as const, description: item.description, explicitness: item.maximumExplicitness })), ...candidate.suggestedRequiredClues.map((item) => ({ id: newId(), kind: 'required' as const, description: item.description, explicitness: item.maximumExplicitness })), ...existingClueRules.map((item) => ({ id: item.id, kind: item.ruleKind, description: item.description, explicitness: item.maximumExplicitness }))]);
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const charactersByName = useMemo(() => entities.filter((entity) => entity.type === 'character'), [entities]);
  const revealChapter = chapters.find((chapter) => chapter.id === revealChapterId);

  useEffect(() => { const savedStep = window.localStorage.getItem(`storymemory.reveal-wizard.${projectId}.${candidate.temporaryId}.step`); if (savedStep) setStep(Math.min(6, Math.max(1, Number(savedStep)))); }, [candidate.temporaryId, projectId]);
  useEffect(() => { window.localStorage.setItem(`storymemory.reveal-wizard.${projectId}.${candidate.temporaryId}.step`, String(step)); }, [candidate.temporaryId, projectId, step]);
  const updateEntry = (setter: React.Dispatch<React.SetStateAction<TimelineEntry[]>>, id: string, patch: Partial<TimelineEntry>) => setter((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const addCharacter = () => setCharacters((items) => [...items, { id: newId(), entityId: '', entries: [emptyEntry()] }]);
  const addClue = (kind: ClueKind) => setClues((items) => [...items, { id: newId(), kind, description: '', explicitness: 'subtle' }]);
  const save = async (mode: 'draft' | 'activate') => {
    if (!title.trim() || !truth.trim()) { setError('Titel und objektive Wahrheit sind erforderlich.'); return; }
    if (mode === 'activate' && !authorConfirmed) { setError('Bestätige zuerst ausdrücklich, dass diese Aussage objektiv wahr ist.'); return; }
    if (revealOffset && (!Number.isInteger(Number(revealOffset)) || Number(revealOffset) < 0)) { setError('Die Position innerhalb der Szene muss eine gültige Unicode-Position sein.'); return; }
    setBusy(mode); setError('');
    try {
      const subjectId = existingContract?.subjectEntityId ?? candidate.temporaryId;
      const contractId = existingContract?.id ?? candidate.temporaryId;
      const status = mode === 'activate' ? 'confirmed' as const : 'proposed' as const;
      const confirmed = mode === 'activate';
      const stateInput = (entry: TimelineEntry, audienceKind: 'reader' | 'character', characterEntityId?: string, index = 0) => ({ id: `${contractId}-${audienceKind}-${characterEntityId ?? 'reader'}-${entry.id}-${index}`, projectId, contractId, audienceKind, characterEntityId, knowledgeLevel: entry.level, beliefText: entry.belief || entry.description, validFromPosition: position(chapters, entry.chapterId, entry.sceneId), validUntilPosition: entry.untilChapterId ? position(chapters, entry.untilChapterId, entry.untilSceneId) : undefined, status, authorConfirmed: confirmed });
      const audienceStates = readerTimeline.map((entry, index) => stateInput(entry, 'reader', undefined, index));
      characters.forEach((path) => { if (!path.entityId) return; path.entries.forEach((entry, index) => audienceStates.push(stateInput(entry, 'character', path.entityId, index))); });
      const clueRules = clues.filter((item) => item.description.trim()).map((item) => ({ id: `${contractId}-clue-${item.id}`, projectId, contractId, ruleKind: item.kind, clueType: 'foreshadowing', description: item.description, maximumExplicitness: item.explicitness, status, authorConfirmed: confirmed }));
      const revealPosition = revealChapter ? position(chapters, revealChapter.id, revealSceneId, revealOffset ? Number(revealOffset) : undefined) : {};
      const result = await repository.activateRevealContractBundle({ mode, projectId, subjectEntity: { id: subjectId, name: title.trim(), type: subjectType, description: truth.trim(), tags: ['reveal'] }, contract: { id: contractId, projectId, subjectEntityId: subjectId, title: title.trim(), truthStatement: truth.trim(), scope: 'book', status, authorConfirmed: confirmed, revealState, plannedRevealBookId: revealBookId || revealPosition.bookId, plannedRevealChapterId: revealPosition.chapterId, plannedRevealSceneId: revealPosition.sceneId, plannedRevealOffset: revealPosition.offset, revealConditionText: condition.trim(), notes: 'Aus dem geführten Reveal-Wizard.' }, audienceStates, clueRules });
      window.localStorage.removeItem(`storymemory.reveal-wizard.${projectId}.${candidate.temporaryId}.step`);
      await onSaved?.({ mode, artifactId: result.contract.id }); onClose();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Der Reveal-Bundle konnte nicht gespeichert werden.'); } finally { setBusy(''); }
  };
  const selectedCharacter = (path: CharacterPath) => charactersByName.find((entity) => entity.id === path.entityId);
  const timelineEditor = (entry: TimelineEntry, setter: React.Dispatch<React.SetStateAction<TimelineEntry[]>>, allowFalseBelief = false) => <div className="wizard-timeline-row" key={entry.id}><div className="form-grid"><label className="field-label">Ab Kapitel<select value={entry.chapterId} onChange={(event) => updateEntry(setter, entry.id, { chapterId: event.target.value, sceneId: '' })}><option value="">Projektanfang</option>{chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><label className="field-label">Ab Szene<select value={entry.sceneId} onChange={(event) => updateEntry(setter, entry.id, { sceneId: event.target.value })} disabled={!entry.chapterId}><option value="">Kapitelanfang</option>{chapters.find((chapter) => chapter.id === entry.chapterId)?.scenes.map((scene) => <option key={scene.id} value={scene.id}>{scene.title}</option>)}</select></label><label className="field-label">Wissensstand<select value={entry.level} onChange={(event) => updateEntry(setter, entry.id, { level: event.target.value as RevealKnowledgeLevel })}>{Object.entries(levelLabels).filter(([key]) => allowFalseBelief || key !== 'false_belief').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><label className="field-label">Beschreibung oder Überzeugung<textarea rows={2} value={entry.belief || entry.description} onChange={(event) => updateEntry(setter, entry.id, { belief: event.target.value, description: event.target.value })} /></label><div className="form-grid"><label className="field-label">Gültig bis Kapitel<select value={entry.untilChapterId} onChange={(event) => updateEntry(setter, entry.id, { untilChapterId: event.target.value, untilSceneId: '' })}><option value="">Ohne Ende</option>{chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><label className="field-label">Gültig bis Szene<select value={entry.untilSceneId} onChange={(event) => updateEntry(setter, entry.id, { untilSceneId: event.target.value })} disabled={!entry.untilChapterId}><option value="">Kapitelende</option>{chapters.find((chapter) => chapter.id === entry.untilChapterId)?.scenes.map((scene) => <option key={scene.id} value={scene.id}>{scene.title}</option>)}</select></label></div><button className="icon-button" aria-label="Wissensstufe entfernen" onClick={() => setter((items) => items.filter((item) => item.id !== entry.id))}><X size={14} /></button></div>;
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal reveal-wizard"><div className="modal-head"><div><span className="eyebrow">GEHEIMNIS & ENTHÜLLUNG · SCHRITT {step} VON 6</span><h2>{['', 'Was ist wirklich wahr?', 'Was weiß der Leser?', 'Wer weiß was?', 'Welche Hinweise sind erlaubt?', 'Wann wird die Wahrheit enthüllt?', 'Zusammenfassung'][step]}</h2></div><button className="icon-button" onClick={onClose} aria-label="Wizard schließen"><X size={18} /></button></div><div className="wizard-progress">{[1, 2, 3, 4, 5, 6].map((number) => <span key={number} className={number <= step ? 'active' : ''}>{number}</span>)}</div>{error && <div className="save-error" role="alert">{error}</div>}
    {step === 1 && <div className="wizard-step"><p>StoryMemory darf diese Wahrheit intern kennen. Sie wird erst nach deiner ausdrücklichen Aktivierung als verbindliche Regel verwendet.</p><label className="field-label">Titel<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="field-label">Objektive Wahrheit<textarea rows={4} value={truth} onChange={(event) => setTruth(event.target.value)} /></label><label className="field-label">Einordnung<select value={subjectType} onChange={(event) => setSubjectType(event.target.value as RevealCandidateSubjectType)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field-label">Sichtbarkeit<select value={revealState} onChange={(event) => setRevealState(event.target.value as typeof revealState)}><option value="author_only">Nur für dich</option><option value="foreshadowed">Wird angedeutet</option><option value="reader_revealed">Leser kennt es</option></select></label><label className="checkline"><input type="checkbox" checked={authorConfirmed} onChange={(event) => setAuthorConfirmed(event.target.checked)} /> Ja, diese Aussage ist objektiv wahr</label></div>}
    {step === 2 && <div className="wizard-step"><p>Diese Liste beschreibt ausschließlich, was der Leser zu welchem Zeitpunkt weiß.</p>{readerTimeline.map((entry) => timelineEditor(entry, setReaderTimeline))}<button className="text-button" onClick={() => setReaderTimeline((items) => [...items, emptyEntry()])}><Plus size={13} /> Weitere Leser-Stufe</button></div>}
    {step === 3 && <div className="wizard-step"><p>Wähle jede Figur ausdrücklich aus. StoryMemory führt Figuren nicht allein über Namen zusammen.</p>{characters.map((path) => <section className="wizard-character-path" key={path.id}><label className="field-label">Figur<select value={path.entityId} onChange={(event) => setCharacters((items) => items.map((item) => item.id === path.id ? { ...item, entityId: event.target.value } : item))}><option value="">Figur auswählen</option>{charactersByName.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><strong>{selectedCharacter(path)?.name ?? 'Noch keine Figur ausgewählt'}</strong>{path.entries.map((entry) => timelineEditor(entry, (update) => setCharacters((items) => items.map((item) => item.id === path.id ? { ...item, entries: update instanceof Function ? update(item.entries) : update } : item)), true))}<button className="text-button" onClick={() => setCharacters((items) => items.map((item) => item.id === path.id ? { ...item, entries: [...item.entries, emptyEntry()] } : item))}><Plus size={13} /> Weitere Wissensstufe</button></section>)}<button className="ghost-button" onClick={addCharacter}><Plus size={13} /> Figur hinzufügen</button></div>}
    {step === 4 && <div className="wizard-step">{(['allowed', 'forbidden', 'required'] as ClueKind[]).map((kind) => <section className="wizard-clue-group" key={kind}><h3>{clueLabels[kind]}</h3>{clues.filter((item) => item.kind === kind).map((item) => <div className="wizard-row" key={item.id}><input aria-label="Hinweis" value={item.description} placeholder="Beschreibe den Hinweis" onChange={(event) => setClues((items) => items.map((entry) => entry.id === item.id ? { ...entry, description: event.target.value } : entry))} /><select aria-label="Hinweisstärke" value={item.explicitness} onChange={(event) => setClues((items) => items.map((entry) => entry.id === item.id ? { ...entry, explicitness: event.target.value as RevealCandidateClue['maximumExplicitness'] } : entry))}><option value="subtle">Sehr subtil</option><option value="suggestive">Auffällig</option><option value="strong">Stark</option><option value="direct">Direkt</option></select><button className="icon-button" onClick={() => setClues((items) => items.filter((entry) => entry.id !== item.id))} aria-label="Hinweis entfernen"><X size={14} /></button></div>)}<button className="text-button" onClick={() => addClue(kind)}><Plus size={13} /> Hinweis hinzufügen</button></section>)}</div>}
    {step === 5 && <div className="wizard-step"><p>Der Enthüllungspunkt ist unabhängig von der Leser-Timeline. Du kannst ihn zunächst offen lassen.</p><div className="form-grid"><label className="field-label">Band<select value={revealBookId} onChange={(event) => setRevealBookId(event.target.value)}><option value="">Noch nicht festgelegt</option>{books.map((book) => <option key={book.id} value={book.id}>{book.title}</option>)}</select></label><label className="field-label">Kapitel<select value={revealChapterId} onChange={(event) => { setRevealChapterId(event.target.value); setRevealSceneId(''); }}><option value="">Noch nicht festgelegt</option>{chapters.filter((chapter) => !revealBookId || chapter.bookId === revealBookId).map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><label className="field-label">Szene<select value={revealSceneId} onChange={(event) => setRevealSceneId(event.target.value)} disabled={!revealChapter}><option value="">Kapitelanfang</option>{revealChapter?.scenes.map((scene) => <option key={scene.id} value={scene.id}>{scene.title}</option>)}</select></label><label className="field-label">Position in der Szene (optional)<input inputMode="numeric" value={revealOffset} onChange={(event) => setRevealOffset(event.target.value)} placeholder="Unicode-Position" /></label></div><label className="field-label">Was muss geschehen?<textarea rows={4} value={condition} onChange={(event) => setCondition(event.target.value)} /></label></div>}
    {step === 6 && <div className="wizard-step"><p>Prüfe deine Angaben. Erst die ausdrückliche Aktivierung macht sie zu verbindlichen Schreib- und Prüfregeln.</p><dl className="reveal-summary"><dt>Objektive Wahrheit</dt><dd>{truth || 'Noch offen'}</dd><dt>Leser-Timeline</dt><dd>{readerTimeline.length} Wissensstufen</dd><dt>Figuren-Timelines</dt><dd>{characters.filter((item) => item.entityId).length} Figuren</dd><dt>Enthüllungspunkt</dt><dd>{revealChapter?.title ?? 'Noch nicht festgelegt'}</dd><dt>Hinweise</dt><dd>{clues.length}</dd></dl><div className="modal-actions"><button className="ghost-button" disabled={busy !== ''} onClick={() => void save('draft')}>Als unbestätigten Entwurf speichern</button><button className="primary-button" disabled={busy !== ''} onClick={() => void save('activate')}><Check size={15} /> Geheimnis und Wissensregeln aktivieren</button></div></div>}
    {step !== 6 && <div className="modal-actions"><button className="ghost-button" onClick={() => step === 1 ? onClose() : setStep((value) => value - 1)}><ArrowLeft size={15} /> Zurück</button><button className="primary-button" onClick={() => setStep((value) => Math.min(6, value + 1))}>Weiter <ArrowRight size={15} /></button></div>}
  </div></div>;
}
