#![allow(dead_code)]

mod commands;
mod database;
mod models;
mod providers;
mod services;

use database::DbState;
use providers::codex::CodexRuntimeState;
use std::sync::Arc;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .setup(|app| {
            let state = DbState::open(app.handle())?;
            app.manage(state);
            app.manage(Arc::new(CodexRuntimeState::default()));
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::load_workspace,
            commands::create_project,
            commands::import_manuscript,
            commands::create_chapter,
            commands::update_chapter,
            commands::create_scene,
            commands::update_scene,
            commands::create_scene_version,
            commands::list_scene_versions,
            commands::restore_scene_version,
            commands::get_editor_preferences,
            commands::save_editor_preferences,
            commands::list_story_entities,
            commands::save_story_entity,
            commands::create_story_entity,
            commands::update_story_entity,
            commands::archive_story_entity,
            commands::get_story_entity,
            commands::create_source_reference,
            commands::list_source_references,
            commands::create_bible_update_run,
            commands::list_bible_update_runs,
            commands::list_bible_proposals,
            commands::save_bible_proposals,
            commands::review_bible_proposal,
            commands::complete_bible_review,
            commands::database_info,
            commands::check_local_languagetool,
            commands::provider_status,
            commands::get_ai_provider_settings,
            commands::save_ai_provider_settings,
            commands::get_codex_provider_status,
            commands::run_codex_task,
            commands::cancel_codex_task,
            commands::get_lore_metadata,
            commands::save_lore_metadata,
            commands::get_character_profile,
            commands::save_character_profile,
            commands::list_character_scene_states,
            commands::save_character_scene_state,
            commands::get_project_style,
            commands::save_project_style,
            commands::create_project_style_analysis_run,
            commands::complete_project_style_analysis_run,
            commands::fail_project_style_analysis_run,
            commands::list_project_style_analysis_runs,
            commands::save_project_style_observations,
            commands::list_project_style_observations,
            commands::review_project_style_observation,
            commands::list_narrative_summaries,
            commands::save_narrative_summary,
            commands::mark_narrative_summary_outdated,
            commands::review_narrative_summary,
            commands::list_style_references,
            commands::create_style_reference,
            commands::update_style_reference,
            commands::delete_style_reference,
            commands::create_lore_entry,
            commands::list_story_entity_relations,
            commands::create_story_entity_relation,
            commands::delete_story_entity_relation,
            commands::list_project_rules,
            commands::save_project_rule,
            commands::delete_project_rule,
            commands::list_project_rule_proposals,
            commands::save_project_rule_proposal,
            commands::review_project_rule_proposal,
            commands::list_continuity_state_ledger,
            commands::save_continuity_state_entry,
            commands::get_state_at_position,
            commands::get_continuity_review_settings,
            commands::save_continuity_review_settings,
            commands::create_continuity_review_run,
            commands::update_continuity_review_run_status,
            commands::list_continuity_review_runs,
            commands::list_continuity_review_findings,
            commands::save_continuity_review_findings,
            commands::review_continuity_finding,
            commands::list_plot_thread_lifecycles,
            commands::save_plot_thread_lifecycle,
            commands::list_plot_thread_lifecycle_proposals,
            commands::save_plot_thread_lifecycle_proposal,
            commands::review_plot_thread_lifecycle_proposal,
            commands::create_manuscript_analysis_job,
            commands::list_manuscript_analysis_jobs,
            commands::get_manuscript_analysis_job,
            commands::list_manuscript_analysis_units,
            commands::update_manuscript_analysis_job,
            commands::update_manuscript_analysis_unit,
            commands::list_manuscript_analysis_draft_ledger,
            commands::replace_manuscript_analysis_draft_ledger,
            commands::review_manuscript_analysis_draft_ledger,
            commands::list_character_voice_patterns,
            commands::save_character_voice_pattern,
            commands::delete_character_voice_pattern,
            commands::list_character_experiences,
            commands::save_character_experience,
            commands::delete_character_experience,
            commands::list_character_dialogue_memories,
            commands::save_character_dialogue_memory,
            commands::delete_character_dialogue_memory,
            commands::list_relationship_memories,
            commands::save_relationship_memory,
            commands::delete_relationship_memory,
            commands::list_character_knowledge_states,
            commands::list_character_knowledge_history,
            commands::save_character_knowledge_state,
            commands::delete_character_knowledge_state,
            commands::list_character_memory_evidence,
            commands::add_character_memory_evidence,
            commands::delete_character_memory_evidence,
            commands::create_character_memory_update_run,
            commands::list_character_memory_update_runs,
            commands::save_character_memory_proposals,
            commands::list_character_memory_proposals,
            commands::review_character_memory_proposal,
            commands::complete_character_memory_review,
            commands::get_story_direction,
            commands::save_story_direction,
            commands::get_writing_preferences,
            commands::save_writing_preferences,
            commands::create_chapter_generation_job,
            commands::list_chapter_generation_jobs,
            commands::update_chapter_generation_job_status,
            commands::get_chapter_generation_plan,
            commands::save_chapter_generation_plan,
            commands::list_chapter_generation_sections,
            commands::save_chapter_generation_section,
            commands::list_chapter_generation_draft_ledger,
            commands::replace_chapter_generation_draft_ledger,
            commands::supersede_chapter_generation_draft_ledger_from,
            commands::list_chapter_generation_reviews,
            commands::save_chapter_generation_reviews,
            commands::delete_chapter_generation_reviews_for_section,
            commands::update_chapter_generation_review_status,
            commands::accept_chapter_generation_job,
            commands::accept_chapter_generation_context_override
        ])
        .run(tauri::generate_context!())
        .expect("error while running StoryMemory");
}
